// The video menu. Every video has a 3-digit request code; the first digit
// groups it by genre (1xx pop, 2xx rock, 3xx 80s, 4xx hip-hop, 5xx latin,
// 6xx funk, 7xx indie, 8xx electronic). 9xx is reserved for videos viewers
// add themselves. Add entries freely:
// { code: "123", id: "<YouTube video id>", title: "Song", artist: "Artist", genre: "pop" }
// Videos that refuse to embed are skipped automatically at runtime.
window.VIDEO_POOL = [
  { code: "101", id: "dQw4w9WgXcQ", title: "Never Gonna Give You Up", artist: "Rick Astley", genre: "pop" },
  { code: "501", id: "kJQP7kiw5Fk", title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", genre: "latin" },
  { code: "102", id: "JGwWNGJdvx8", title: "Shape of You", artist: "Ed Sheeran", genre: "pop" },
  { code: "601", id: "OPf0YbXqDm0", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", genre: "funk" },
  { code: "103", id: "9bZkp7q19f0", title: "Gangnam Style", artist: "PSY", genre: "pop" },
  { code: "201", id: "fJ9rUzIMcZQ", title: "Bohemian Rhapsody", artist: "Queen", genre: "rock" },
  { code: "202", id: "hTWKbfoikeg", title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "rock" },
  { code: "104", id: "YQHsXMglC9A", title: "Hello", artist: "Adele", genre: "pop" },
  { code: "105", id: "hLQl3WQQoQ0", title: "Someone Like You", artist: "Adele", genre: "pop" },
  { code: "106", id: "rYEDA3JcQqw", title: "Rolling in the Deep", artist: "Adele", genre: "pop" },
  { code: "107", id: "CevxZvSJLk8", title: "Roar", artist: "Katy Perry", genre: "pop" },
  { code: "108", id: "0KSOMA3QBU0", title: "Dark Horse", artist: "Katy Perry", genre: "pop" },
  { code: "401", id: "RgKAFK5djSk", title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", genre: "hip-hop" },
  { code: "801", id: "60ItHLz5WEA", title: "Faded", artist: "Alan Walker", genre: "electronic" },
  { code: "502", id: "pRpeEdMmmQ0", title: "Waka Waka", artist: "Shakira", genre: "latin" },
  { code: "109", id: "2Vv-BfVoq4g", title: "Perfect", artist: "Ed Sheeran", genre: "pop" },
  { code: "110", id: "lp-EO5I60KA", title: "Thinking Out Loud", artist: "Ed Sheeran", genre: "pop" },
  { code: "111", id: "e-ORhEE9VVg", title: "Blank Space", artist: "Taylor Swift", genre: "pop" },
  { code: "112", id: "nfWlot6h_JM", title: "Shake It Off", artist: "Taylor Swift", genre: "pop" },
  { code: "113", id: "hT_nvWreIhg", title: "Counting Stars", artist: "OneRepublic", genre: "pop" },
  { code: "301", id: "djV11Xbc914", title: "Take On Me", artist: "a-ha", genre: "80s" },
  { code: "302", id: "btPJPFnesV4", title: "Eye of the Tiger", artist: "Survivor", genre: "80s" },
  { code: "303", id: "PIb6AZdTr-A", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", genre: "80s" },
  { code: "203", id: "lDK9QqIzhwk", title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "rock" },
  { code: "204", id: "1w7OgIMMRc4", title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "rock" },
  { code: "205", id: "v2AC41dglnM", title: "Thunderstruck", artist: "AC/DC", genre: "rock" },
  { code: "304", id: "Zi_XLOBDo_Y", title: "Billie Jean", artist: "Michael Jackson", genre: "80s" },
  { code: "305", id: "sOnqjkJTMaA", title: "Thriller", artist: "Michael Jackson", genre: "80s" },
  { code: "114", id: "4NRXx6U8ABQ", title: "Blinding Lights", artist: "The Weeknd", genre: "pop" },
  { code: "402", id: "YVkUvmDQ3HY", title: "Without Me", artist: "Eminem", genre: "hip-hop" },
  { code: "403", id: "uelHwf8o7_U", title: "Love The Way You Lie", artist: "Eminem ft. Rihanna", genre: "hip-hop" },
  { code: "404", id: "QK8mJJJvaes", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis", genre: "hip-hop" },
  { code: "701", id: "8UVNT4wvIGY", title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", genre: "indie" },
  { code: "206", id: "bx1Bh8ZvH84", title: "Wonderwall", artist: "Oasis", genre: "rock" },
  { code: "207", id: "1lyu1KKwC74", title: "Bitter Sweet Symphony", artist: "The Verve", genre: "rock" },
  { code: "702", id: "gGdGFtwCNBE", title: "Mr. Brightside", artist: "The Killers", genre: "indie" },
  { code: "208", id: "0J2QdDbelmY", title: "Seven Nation Army", artist: "The White Stripes", genre: "rock" },
  { code: "209", id: "Soa3gO7tL-c", title: "Boulevard of Broken Dreams", artist: "Green Day", genre: "rock" },
  { code: "210", id: "L_jWHffIx5E", title: "All Star", artist: "Smash Mouth", genre: "rock" },
  { code: "602", id: "Gs069dndIYk", title: "September", artist: "Earth, Wind & Fire", genre: "funk" },
  { code: "115", id: "09R8_2nJtjg", title: "Sugar", artist: "Maroon 5", genre: "pop" },
  { code: "802", id: "papuvlVeZg8", title: "Rockabye", artist: "Clean Bandit ft. Sean Paul & Anne-Marie", genre: "electronic" },
  { code: "116", id: "k2qgadSvNyU", title: "New Rules", artist: "Dua Lipa", genre: "pop" },
  { code: "211", id: "ktvTqknDobU", title: "Radioactive", artist: "Imagine Dragons", genre: "rock" },
  { code: "212", id: "7wtfhZwyrcc", title: "Believer", artist: "Imagine Dragons", genre: "rock" },
  { code: "213", id: "fKopy74weus", title: "Thunder", artist: "Imagine Dragons", genre: "rock" },
  { code: "117", id: "YykjpeuMNEk", title: "Hymn for the Weekend", artist: "Coldplay", genre: "pop" },
  { code: "118", id: "dvgZkm1xWPE", title: "Viva La Vida", artist: "Coldplay", genre: "pop" },
  { code: "703", id: "RBumgq5yVrA", title: "Let Her Go", artist: "Passenger", genre: "indie" },
  { code: "603", id: "y6Sxv-sUYtM", title: "Happy", artist: "Pharrell Williams", genre: "funk" },
  { code: "119", id: "450p7goxZqg", title: "All of Me", artist: "John Legend", genre: "pop" },
  { code: "120", id: "2vjPBrBU-TM", title: "Chandelier", artist: "Sia", genre: "pop" },
];
