// The video menu. Every video has a 4-digit request code. Each genre owns a block of
// codes (spare codes are left in every block so adding videos never renumbers anything):
//   1000-1099  pop
//   1100-1199  rock
//   1200-1499  70s
//   1500-1799  80s
//   1800-1999  90s
//   2000-2199  90s-rock
//   2200-2399  2000s
//   2400-2499  hip-hop
//   2500-2599  latin
//   2600-2699  funk
//   2700-2799  indie
//   2800-2899  electronic
//   2900-2999  country
//   9900-9999  reserved for videos viewers add themselves
// Add entries freely using the next unused code in the genre's block:
// { code: "1060", id: "<YouTube video id>", title: "Song", artist: "Artist", genre: "pop" }
// Videos that refuse to embed are skipped automatically at runtime.
window.VIDEO_POOL = [
  { code: "1000", id: "dQw4w9WgXcQ", title: "Never Gonna Give You Up", artist: "Rick Astley", genre: "pop" },
  { code: "1001", id: "JGwWNGJdvx8", title: "Shape of You", artist: "Ed Sheeran", genre: "pop" },
  { code: "1002", id: "9bZkp7q19f0", title: "Gangnam Style", artist: "PSY", genre: "pop" },
  { code: "1003", id: "YQHsXMglC9A", title: "Hello", artist: "Adele", genre: "pop" },
  { code: "1004", id: "hLQl3WQQoQ0", title: "Someone Like You", artist: "Adele", genre: "pop" },
  { code: "1005", id: "rYEDA3JcQqw", title: "Rolling in the Deep", artist: "Adele", genre: "pop" },
  { code: "1006", id: "CevxZvSJLk8", title: "Roar", artist: "Katy Perry", genre: "pop" },
  { code: "1007", id: "0KSOMA3QBU0", title: "Dark Horse", artist: "Katy Perry", genre: "pop" },
  { code: "1008", id: "2Vv-BfVoq4g", title: "Perfect", artist: "Ed Sheeran", genre: "pop" },
  { code: "1009", id: "lp-EO5I60KA", title: "Thinking Out Loud", artist: "Ed Sheeran", genre: "pop" },
  { code: "1010", id: "e-ORhEE9VVg", title: "Blank Space", artist: "Taylor Swift", genre: "pop" },
  { code: "1011", id: "nfWlot6h_JM", title: "Shake It Off", artist: "Taylor Swift", genre: "pop" },
  { code: "1012", id: "hT_nvWreIhg", title: "Counting Stars", artist: "OneRepublic", genre: "pop" },
  { code: "1013", id: "4NRXx6U8ABQ", title: "Blinding Lights", artist: "The Weeknd", genre: "pop" },
  { code: "1014", id: "09R8_2nJtjg", title: "Sugar", artist: "Maroon 5", genre: "pop" },
  { code: "1015", id: "k2qgadSvNyU", title: "New Rules", artist: "Dua Lipa", genre: "pop" },
  { code: "1016", id: "YykjpeuMNEk", title: "Hymn for the Weekend", artist: "Coldplay", genre: "pop" },
  { code: "1017", id: "dvgZkm1xWPE", title: "Viva La Vida", artist: "Coldplay", genre: "pop" },
  { code: "1018", id: "450p7goxZqg", title: "All of Me", artist: "John Legend", genre: "pop" },
  { code: "1019", id: "2vjPBrBU-TM", title: "Chandelier", artist: "Sia", genre: "pop" },
  { code: "1020", id: "KRaWnd3LJfs", title: "Payphone ft. Wiz Khalifa", artist: "Maroon 5", genre: "pop" },
  { code: "1021", id: "psuRGfAaju4", title: "Fireflies", artist: "Owl City", genre: "pop" },
  { code: "1022", id: "fwK7ggA3-bU", title: "One More Night", artist: "Maroon 5", genre: "pop" },
  { code: "1023", id: "fWNaR-rxAic", title: "Call Me Maybe", artist: "Carly Rae Jepsen", genre: "pop" },
  { code: "1024", id: "kVpv8-5XWOI", title: "Hey, Soul Sister", artist: "Train", genre: "pop" },
  { code: "1025", id: "M11SvDtPBhA", title: "Party In The U.S.A.", artist: "Miley Cyrus", genre: "pop" },
  { code: "1026", id: "QGJuMBdaqIw", title: "Firework", artist: "Katy Perry", genre: "pop" },
  { code: "1027", id: "qrO4YZeyl0I", title: "Bad Romance", artist: "Lady Gaga", genre: "pop" },
  { code: "1028", id: "bESGLojNYSo", title: "Poker Face", artist: "Lady Gaga", genre: "pop" },
  { code: "1029", id: "uSD4vsh1zDA", title: "I Gotta Feeling", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "1030", id: "4m48GqaOz90", title: "Boom Boom Pow", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "1031", id: "fLexgOxsZu0", title: "The Lazy Song", artist: "Bruno Mars", genre: "pop" },
  { code: "1032", id: "iEPTlhBmwRg", title: "Moves Like Jagger ft. Christina Aguilera", artist: "Maroon 5", genre: "pop" },
  { code: "1033", id: "Vysgv7qVYTo", title: "Dynamite", artist: "Taio Cruz", genre: "pop" },
  { code: "1034", id: "6g6g2mvItp4", title: "Misery", artist: "Maroon 5", genre: "pop" },
  { code: "1035", id: "ZaI2IlHwmgQ", title: "Pump It", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "1036", id: "kTHNpusq654", title: "Hot N Cold", artist: "Katy Perry", genre: "pop" },
  { code: "1037", id: "Y7ix6RITXM0", title: "Maps", artist: "Maroon 5", genre: "pop" },
  { code: "1038", id: "F57P9C4SAW4", title: "California Gurls ft. Snoop Dogg", artist: "Katy Perry", genre: "pop" },
  { code: "1039", id: "LjhCEhWiKXk", title: "Just The Way You Are", artist: "Bruno Mars", genre: "pop" },
  { code: "1040", id: "ZyhrYis509A", title: "Barbie Girl", artist: "Aqua", genre: "pop" },
  { code: "1041", id: "NOubzHCUt48", title: "Die Young", artist: "Ke$ha", genre: "pop" },
  { code: "1042", id: "VuNIsY6JdUw", title: "You Belong With Me", artist: "Taylor Swift", genre: "pop" },
  { code: "1043", id: "3OnnDqH6Wj8", title: "Good Feeling", artist: "Flo Rida", genre: "pop" },
  { code: "1044", id: "QJO3ROT-A4E", title: "What Makes You Beautiful", artist: "One Direction", genre: "pop" },
  { code: "1045", id: "hHUbLv4ThOo", title: "Timber", artist: "Pitbull, Ke$ha", genre: "pop" },
  { code: "1046", id: "-YICuUtkjlg", title: "Wrecking Ball", artist: "Miley Cyrus", genre: "pop" },
  { code: "1047", id: "qpgTC9MDx1o", title: "Animals", artist: "Maroon 5", genre: "pop" },
  { code: "1048", id: "z3zdIHDTbg0", title: "Made in the USA", artist: "Demi Lovato", genre: "pop" },
  { code: "1049", id: "iP6XpLQM2Cs", title: "TiK ToK", artist: "Ke$ha", genre: "pop" },
  { code: "1050", id: "WA4iX5D9Z64", title: "We Are Never Ever Getting Back Together", artist: "Taylor Swift", genre: "pop" },
  { code: "1051", id: "7PCkvCPvDXk", title: "All About That Bass", artist: "Meghan Trainor", genre: "pop" },
  { code: "1052", id: "4fndeDfaWCg", title: "I Want It That Way", artist: "Backstreet Boys", genre: "pop" },
  { code: "1053", id: "bTXJQ5ql5Fw", title: "Time of Our Lives", artist: "Pitbull, Ne-Yo", genre: "pop" },
  { code: "1054", id: "7Xf-Lesrkuc", title: "Drops Of Jupiter (Tell Me)", artist: "Train", genre: "pop" },
  { code: "1055", id: "qQzdAsjWGPg", title: "My Way", artist: "Frank Sinatra", genre: "pop" },
  { code: "1056", id: "kffacxfA7G4", title: "Baby ft. Ludacris", artist: "Justin Bieber", genre: "pop" },
  { code: "1057", id: "75IMChOtf9s", title: "The Show Must Go On", artist: "Hazbin Hotel", genre: "pop" },
  { code: "1058", id: "7OwRqCFuH9k", title: "Poison (Official Remix)", artist: "Hazbin Hotel", genre: "pop" },
  { code: "1100", id: "fJ9rUzIMcZQ", title: "Bohemian Rhapsody", artist: "Queen", genre: "rock" },
  { code: "1101", id: "hTWKbfoikeg", title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "rock" },
  { code: "1102", id: "lDK9QqIzhwk", title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "rock" },
  { code: "1103", id: "1w7OgIMMRc4", title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "rock" },
  { code: "1104", id: "v2AC41dglnM", title: "Thunderstruck", artist: "AC/DC", genre: "rock" },
  { code: "1105", id: "bx1Bh8ZvH84", title: "Wonderwall", artist: "Oasis", genre: "rock" },
  { code: "1106", id: "1lyu1KKwC74", title: "Bitter Sweet Symphony", artist: "The Verve", genre: "rock" },
  { code: "1107", id: "0J2QdDbelmY", title: "Seven Nation Army", artist: "The White Stripes", genre: "rock" },
  { code: "1108", id: "Soa3gO7tL-c", title: "Boulevard of Broken Dreams", artist: "Green Day", genre: "rock" },
  { code: "1109", id: "L_jWHffIx5E", title: "All Star", artist: "Smash Mouth", genre: "rock" },
  { code: "1110", id: "ktvTqknDobU", title: "Radioactive", artist: "Imagine Dragons", genre: "rock" },
  { code: "1111", id: "7wtfhZwyrcc", title: "Believer", artist: "Imagine Dragons", genre: "rock" },
  { code: "1112", id: "fKopy74weus", title: "Thunder", artist: "Imagine Dragons", genre: "rock" },
  { code: "1113", id: "CxKWTzr-k6s", title: "Even Flow", artist: "Pearl Jam", genre: "rock" },
  { code: "1114", id: "0mYBSayCsH0", title: "I'm A Believer", artist: "Smash Mouth", genre: "rock" },
  { code: "1115", id: "3afXXsJwYZo", title: "Joker and the Thief", artist: "Wolfmother", genre: "rock" },
  { code: "1116", id: "I_2D8Eo15wE", title: "Black Betty", artist: "Ram Jam", genre: "rock" },
  { code: "1117", id: "UZm3Ad3gTSI", title: "The Unforgiven (Live, Madrid 2024)", artist: "Metallica", genre: "rock" },
  { code: "1118", id: "912EG0VhCmk", title: "Fade to Black (Live, Phoenix 2023)", artist: "Metallica", genre: "rock" },
  { code: "1119", id: "CqnU_sJ8V-E", title: "Free Bird", artist: "Lynyrd Skynyrd", genre: "rock" },
  { code: "1120", id: "Aiay8I5IPB8", title: "How You Remind Me", artist: "Nickelback", genre: "rock" },
  { code: "1121", id: "_1hgVcNzvzY", title: "Rockstar", artist: "Nickelback", genre: "rock" },
  { code: "1122", id: "GP7zpdwo3Xo", title: "Far Away", artist: "Nickelback", genre: "rock" },
  { code: "1123", id: "T3rXdeOvhNE", title: "Photograph", artist: "Nickelback", genre: "rock" },
  { code: "1124", id: "_JQiEs32SqQ", title: "Savin' Me", artist: "Nickelback", genre: "rock" },
  { code: "1125", id: "4bE7caE5UGc", title: "Next Contestant", artist: "Nickelback", genre: "rock" },
  { code: "1126", id: "dZLfasMPOU4", title: "Stacy's Mom", artist: "Fountains Of Wayne", genre: "rock" },
  { code: "1127", id: "8SbUC-UaAxE", title: "November Rain", artist: "Guns N' Roses", genre: "rock" },
  { code: "1200", id: "3T1c7GkzRQQ", title: "Roxanne", artist: "The Police", genre: "70s" },
  { code: "1201", id: "wvUQcnfwUUM", title: "In The Summertime", artist: "Mungo Jerry", genre: "70s" },
  { code: "1202", id: "-ihs-vT9T3Q", title: "Night Fever", artist: "Bee Gees", genre: "70s" },
  { code: "1203", id: "mZ6VezKMoRY", title: "No Woman, No Cry (Live at the Rainbow)", artist: "Bob Marley & The Wailers", genre: "70s" },
  { code: "1204", id: "ModISbNyQ8I", title: "Hooray! Hooray! It's a Holi-Holiday", artist: "Boney M.", genre: "70s" },
  { code: "1205", id: "FOt3oQ_k008", title: "Sailing", artist: "Rod Stewart", genre: "70s" },
  { code: "1206", id: "nXiQtD5gcHU", title: "Papa Was a Rollin' Stone", artist: "The Temptations", genre: "70s" },
  { code: "1207", id: "hutlaauYa2c", title: "Sunny", artist: "Boney M.", genre: "70s" },
  { code: "1208", id: "J123lM0RvzM", title: "Heaven Must Be Missing an Angel", artist: "Tavares", genre: "70s" },
  { code: "1209", id: "AZKcl4-tcuo", title: "Life On Mars?", artist: "David Bowie", genre: "70s" },
  { code: "1210", id: "HSNSTerj2Kc", title: "Chirpy Chirpy Cheep Cheep", artist: "Middle of the Road", genre: "70s" },
  { code: "1211", id: "qae25976UgA", title: "Werewolves of London", artist: "Warren Zevon", genre: "70s" },
  { code: "1212", id: "f4uSzrsOQr8", title: "Baby Come Back", artist: "Player", genre: "70s" },
  { code: "1213", id: "OpaCXtahXxk", title: "Kiss You All Over", artist: "Exile", genre: "70s" },
  { code: "1214", id: "T6fVDAjs9f0", title: "When Will I See You Again", artist: "The Three Degrees", genre: "70s" },
  { code: "1215", id: "4cia_v4vxfE", title: "You Ain't Seen Nothing Yet", artist: "Bachman-Turner Overdrive", genre: "70s" },
  { code: "1216", id: "XbAM2_6jKY0", title: "I'm In the Mood for Dancing", artist: "The Nolans", genre: "70s" },
  { code: "1217", id: "Zf53Pg2AkdY", title: "Radar Love", artist: "Golden Earring", genre: "70s" },
  { code: "1218", id: "lcWVL4B-4pI", title: "Blinded by the Light", artist: "Manfred Mann's Earth Band", genre: "70s" },
  { code: "1219", id: "wZkTh_T75QY", title: "Get It On", artist: "T. Rex", genre: "70s" },
  { code: "1220", id: "lP94PlEtsEQ", title: "Long Cool Woman in a Black Dress", artist: "The Hollies", genre: "70s" },
  { code: "1221", id: "tqketmsRz1E", title: "The Ballroom Blitz", artist: "Sweet", genre: "70s" },
  { code: "1222", id: "2-eclUz-RYI", title: "(I Never Promised You a) Rose Garden", artist: "Lynn Anderson", genre: "70s" },
  { code: "1223", id: "Gmq4WIjQxp0", title: "It Never Rains in Southern California", artist: "Albert Hammond", genre: "70s" },
  { code: "1224", id: "7UMnZpMid6Y", title: "Ma Baker", artist: "Boney M.", genre: "70s" },
  { code: "1225", id: "gkqfpkTTy2w", title: "American Woman", artist: "The Guess Who", genre: "70s" },
  { code: "1226", id: "lLLL1KxpYMA", title: "Night Boat to Cairo", artist: "Madness", genre: "70s" },
  { code: "1227", id: "1P17ct4e5OE", title: "Since You've Been Gone", artist: "Rainbow", genre: "70s" },
  { code: "1228", id: "2XeSQVWleqY", title: "Mandy", artist: "Barry Manilow", genre: "70s" },
  { code: "1229", id: "ZyBFxjmJPqk", title: "Wig Wam Bam", artist: "Sweet", genre: "70s" },
  { code: "1230", id: "BR2JtsVumFA", title: "My Sharona", artist: "The Knack", genre: "70s" },
  { code: "1231", id: "hic-dnps6MU", title: "Miss You", artist: "The Rolling Stones", genre: "70s" },
  { code: "1232", id: "MGemtjVtfZM", title: "Cracklin' Rosie", artist: "Neil Diamond", genre: "70s" },
  { code: "1233", id: "Y64211sjSko", title: "Block Buster!", artist: "Sweet", genre: "70s" },
  { code: "1234", id: "FHTeuV2E1q8", title: "One for You, One for Me", artist: "La Bionda", genre: "70s" },
  { code: "1235", id: "KWXtnWy-o0M", title: "Nice and Slow", artist: "Jesse Green", genre: "70s" },
  { code: "1236", id: "ASGgn8bNQuA", title: "Magic", artist: "Pilot", genre: "70s" },
  { code: "1237", id: "m-H0uIH5HHQ", title: "That's Entertainment", artist: "The Jam", genre: "70s" },
  { code: "1238", id: "gQK9k42ongU", title: "Una Paloma Blanca", artist: "George Baker Selection", genre: "70s" },
  { code: "1239", id: "h1qQ1SKNlgY", title: "Le Freak", artist: "Chic", genre: "70s" },
  { code: "1240", id: "QjtD8A-MWBc", title: "Sky High", artist: "Jigsaw", genre: "70s" },
  { code: "1241", id: "b9YyPIiT2pM", title: "Follow Me", artist: "Amanda Lear", genre: "70s" },
  { code: "1242", id: "NM6I-pmV0RA", title: "Little Willy", artist: "Sweet", genre: "70s" },
  { code: "1243", id: "LrjHz5hrupA", title: "Oliver's Army", artist: "Elvis Costello & The Attractions", genre: "70s" },
  { code: "1244", id: "KbI_awR4CKE", title: "Maggie May", artist: "Rod Stewart", genre: "70s" },
  { code: "1245", id: "BHcYFxU4fMo", title: "Play That Funky Music", artist: "Wild Cherry", genre: "70s" },
  { code: "1246", id: "q4b3w6a9cSk", title: "Afternoon Delight", artist: "Starland Vocal Band", genre: "70s" },
  { code: "1247", id: "KX-JeV37Uqw", title: "Billy Don't Be a Hero", artist: "Paper Lace", genre: "70s" },
  { code: "1248", id: "_JALXA3NgsU", title: "Gonna Get Along Without You Now", artist: "Viola Wills", genre: "70s" },
  { code: "1249", id: "QAzESJ62irI", title: "This Town Ain't Big Enough for Both of Us", artist: "Sparks", genre: "70s" },
  { code: "1250", id: "uJ2cEc_TCH8", title: "Cool for Cats", artist: "Squeeze", genre: "70s" },
  { code: "1251", id: "mJpymZpk-t8", title: "D.I.S.C.O.", artist: "Ottawan", genre: "70s" },
  { code: "1252", id: "1QvvByvbwLk", title: "Rock Your Baby", artist: "George McCrae", genre: "70s" },
  { code: "1253", id: "0H6re3PCP3E", title: "Brass in Pocket", artist: "Pretenders", genre: "70s" },
  { code: "1254", id: "RQciegmLPAo", title: "Up the Junction", artist: "Squeeze", genre: "70s" },
  { code: "1255", id: "pkMgs3lFwkQ", title: "Mony Mony", artist: "Tommy James & The Shondells", genre: "70s" },
  { code: "1256", id: "0WGVgfjnLqc", title: "Hit Me With Your Rhythm Stick", artist: "Ian Dury and The Blockheads", genre: "70s" },
  { code: "1257", id: "AQ21CLUQf0E", title: "I Do, I Do, I Do, I Do, I Do", artist: "ABBA", genre: "70s" },
  { code: "1258", id: "tdCY0CgMoq8", title: "I'm Not in Love", artist: "10cc", genre: "70s" },
  { code: "1259", id: "b0l3QWUXVho", title: "Cruel to Be Kind", artist: "Nick Lowe", genre: "70s" },
  { code: "1260", id: "5fgA_yNCeq4", title: "Substitute", artist: "Clout", genre: "70s" },
  { code: "1261", id: "EQfidTOTsLo", title: "Tiger Feet", artist: "Mud", genre: "70s" },
  { code: "1262", id: "jCienKYxJ0c", title: "Shake Your Body (Down to the Ground)", artist: "The Jacksons", genre: "70s" },
  { code: "1263", id: "yUwW108ITzw", title: "Bye Bye Baby", artist: "Bay City Rollers", genre: "70s" },
  { code: "1264", id: "qyD5tAGBP9U", title: "You Make Me Feel Brand New", artist: "The Stylistics", genre: "70s" },
  { code: "1265", id: "hRu7Pt42x6Y", title: "Black Magic Woman (Live)", artist: "Fleetwood Mac", genre: "70s" },
  { code: "1266", id: "jtDQxJlcUxE", title: "Tie a Yellow Ribbon Round the Ole Oak Tree", artist: "Tony Orlando & Dawn", genre: "70s" },
  { code: "1267", id: "7BKKaKT_dtM", title: "Saturday Night", artist: "Bay City Rollers", genre: "70s" },
  { code: "1268", id: "eB0aROCl530", title: "Car Wash", artist: "Rose Royce", genre: "70s" },
  { code: "1269", id: "60a6LpB4zZ8", title: "Friday Night", artist: "Arabesque", genre: "70s" },
  { code: "1270", id: "l3fZuW-aJsg", title: "Shake Your Booty", artist: "KC and the Sunshine Band", genre: "70s" },
  { code: "1271", id: "0Af7ayYIJ9w", title: "Ever Fallen in Love (With Someone You Shouldn't've?)", artist: "Buzzcocks", genre: "70s" },
  { code: "1272", id: "C9lz_yzrGZw", title: "Don't It Make My Brown Eyes Blue", artist: "Crystal Gayle", genre: "70s" },
  { code: "1273", id: "i15ALD6fsUU", title: "Some Girls", artist: "Racey", genre: "70s" },
  { code: "1274", id: "Tn0-6n_dng4", title: "Lady Marmalade", artist: "Labelle", genre: "70s" },
  { code: "1275", id: "ZZ0PZRYin2s", title: "Dream a Little Dream of Me", artist: "Cass Elliot", genre: "70s" },
  { code: "1276", id: "TjL7vO8-NOg", title: "Children of the Revolution", artist: "T. Rex", genre: "70s" },
  { code: "1277", id: "Avvh5H-EPWU", title: "Pop Muzik", artist: "M", genre: "70s" },
  { code: "1278", id: "U0oSHtxdPus", title: "I Only Want to Be with You", artist: "Bay City Rollers", genre: "70s" },
  { code: "1279", id: "VgYczUH-QWQ", title: "Ain't No Stoppin' Us Now", artist: "McFadden & Whitehead", genre: "70s" },
  { code: "1280", id: "NjYgLIicqus", title: "Dancing in the City", artist: "Marshall Hain", genre: "70s" },
  { code: "1281", id: "O0_H3F84Yjk", title: "That's the Way (I Like It)", artist: "KC and the Sunshine Band", genre: "70s" },
  { code: "1282", id: "9f4CyQto-0E", title: "Mr. Big Stuff", artist: "Jean Knight", genre: "70s" },
  { code: "1283", id: "WpT7hbVWJDQ", title: "Arms of Mary", artist: "Sutherland Brothers & Quiver", genre: "70s" },
  { code: "1284", id: "9fYZdQB8w_s", title: "Under the Moon of Love", artist: "Showaddywaddy", genre: "70s" },
  { code: "1285", id: "tkYkeeM8qIA", title: "A Glass of Champagne", artist: "Sailor", genre: "70s" },
  { code: "1286", id: "I3Iw2qYtN8A", title: "Heartbeat – It's a Lovebeat", artist: "The DeFranco Family", genre: "70s" },
  { code: "1287", id: "iJiNohQ-rWc", title: "Sugar Baby Love", artist: "The Rubettes", genre: "70s" },
  { code: "1288", id: "-4VTz7gSHds", title: "If I Can't Have You", artist: "Yvonne Elliman", genre: "70s" },
  { code: "1289", id: "wQPlU5q1CBI", title: "Jumpin' Jack Flash (Live)", artist: "Johnny Winter", genre: "70s" },
  { code: "1290", id: "3B0Y3LUqr1Q", title: "Brown Sugar", artist: "The Rolling Stones", genre: "70s" },
  { code: "1291", id: "BXsosNMI0j4", title: "Young Hearts Run Free", artist: "Candi Staton", genre: "70s" },
  { code: "1292", id: "C7kUDkK70qQ", title: "The Eton Rifles", artist: "The Jam", genre: "70s" },
  { code: "1293", id: "teBV0EoJJY8", title: "Calling Occupants of Interplanetary Craft", artist: "Carpenters", genre: "70s" },
  { code: "1294", id: "ytii7-bUxuk", title: "Shang-A-Lang", artist: "Bay City Rollers", genre: "70s" },
  { code: "1295", id: "jxvPjuREDpE", title: "The Rose", artist: "Bette Midler", genre: "70s" },
  { code: "1296", id: "YHKCHvpYq_8", title: "Boogie Fever", artist: "The Sylvers", genre: "70s" },
  { code: "1297", id: "3GVugJj7BUs", title: "I Was Made for Dancing", artist: "Leif Garrett", genre: "70s" },
  { code: "1298", id: "3zzwbYyvWiU", title: "All Around My Hat", artist: "Steeleye Span", genre: "70s" },
  { code: "1299", id: "sptQj1MPIwg", title: "No Regrets", artist: "The Walker Brothers", genre: "70s" },
  { code: "1300", id: "HiMl4yX1JiA", title: "Blue Bayou (Live)", artist: "Roy Orbison", genre: "70s" },
  { code: "1301", id: "seu2xuMQnIA", title: "I Love to Love", artist: "Tina Charles", genre: "70s" },
  { code: "1302", id: "UWdcZqG02Ls", title: "Jeans On", artist: "David Dundas", genre: "70s" },
  { code: "1303", id: "eWeezUxIzaE", title: "Gypsys, Tramps & Thieves", artist: "Cher", genre: "70s" },
  { code: "1304", id: "iukUMRlaBBE", title: "Autobahn", artist: "Kraftwerk", genre: "70s" },
  { code: "1305", id: "Ww4v2cP-MDo", title: "Welcome Home", artist: "Peters & Lee", genre: "70s" },
  { code: "1306", id: "Szavq0lrFtg", title: "Save Your Kisses for Me", artist: "Brotherhood of Man", genre: "70s" },
  { code: "1307", id: "HiuPND4W6KM", title: "My Boy Lollipop", artist: "Millie", genre: "70s" },
  { code: "1308", id: "quyB8PMTD3o", title: "The Boys Are Back in Town", artist: "Thin Lizzy", genre: "70s" },
  { code: "1309", id: "nAN-LvFOGus", title: "Airport", artist: "The Motors", genre: "70s" },
  { code: "1310", id: "ofDCsRhT57o", title: "Lay Your Love on Me", artist: "Racey", genre: "70s" },
  { code: "1311", id: "9BBc2zTx6s0", title: "Poppa Joe", artist: "Sweet", genre: "70s" },
  { code: "1312", id: "eyJA4t7oJAk", title: "I Am... I Said", artist: "Neil Diamond", genre: "70s" },
  { code: "1313", id: "4MyJHh451Y4", title: "Roll Away the Stone", artist: "Mott the Hoople", genre: "70s" },
  { code: "1314", id: "Hz2Cv6Zb9a0", title: "Shake Your Groove Thing", artist: "Peaches & Herb", genre: "70s" },
  { code: "1315", id: "TfZPp3IF7os", title: "Down by the Lazy River", artist: "The Osmonds", genre: "70s" },
  { code: "1316", id: "lSYxf_1uED0", title: "Raindrops Keep Fallin' on My Head", artist: "B.J. Thomas", genre: "70s" },
  { code: "1317", id: "brxvxksq9CY", title: "SOS", artist: "ABBA", genre: "70s" },
  { code: "1318", id: "2rYYecQN3VM", title: "Born to Be Alive", artist: "Patrick Hernandez", genre: "70s" },
  { code: "1319", id: "UPGiLsdWZdo", title: "Girls Girls Girls", artist: "Sailor", genre: "70s" },
  { code: "1320", id: "lPsa8MJU_50", title: "Jump in My Car", artist: "Ted Mulry Gang", genre: "70s" },
  { code: "1321", id: "ZWKznrEjJK4", title: "I'd Like to Teach the World to Sing", artist: "The New Seekers", genre: "70s" },
  { code: "1322", id: "uF9Q3hnAr88", title: "Band of Gold", artist: "Freda Payne", genre: "70s" },
  { code: "1323", id: "1xt1jA1igk4", title: "Love of My Life", artist: "The Dooleys", genre: "70s" },
  { code: "1324", id: "gjjuY5qetnw", title: "Bang Bang", artist: "B.A. Robertson", genre: "70s" },
  { code: "1325", id: "P90bu9VQBHQ", title: "Draggin' the Line", artist: "Tommy James", genre: "70s" },
  { code: "1326", id: "nOrIloT8Okw", title: "Hurt", artist: "Elvis Presley", genre: "70s" },
  { code: "1327", id: "UyNYL2lUSMs", title: "The Witch Queen of New Orleans", artist: "Redbone", genre: "70s" },
  { code: "1328", id: "coZZaqFfr2g", title: "I'm Henry VIII, I Am", artist: "Herman's Hermits", genre: "70s" },
  { code: "1329", id: "rgX3RRIUH-0", title: "Hold Back the Night", artist: "The Trammps", genre: "70s" },
  { code: "1330", id: "q1OVYFNUZT8", title: "Tears of a Clown", artist: "The Beat", genre: "70s" },
  { code: "1331", id: "1ycOp67eLoM", title: "(Don't Fear) The Reaper", artist: "Blue Öyster Cult", genre: "70s" },
  { code: "1332", id: "Wv8N6zSzL7k", title: "I'm Mandy, Fly Me", artist: "10cc", genre: "70s" },
  { code: "1333", id: "VB4JPQKr9bQ", title: "He's the Greatest Dancer", artist: "Sister Sledge", genre: "70s" },
  { code: "1334", id: "qCVR5XR04Mo", title: "Silly Games", artist: "Janet Kay", genre: "70s" },
  { code: "1335", id: "YriPIujLtsA", title: "Long Haired Lover from Liverpool", artist: "Jimmy Osmond", genre: "70s" },
  { code: "1336", id: "1CzDlk2bnSI", title: "Duke of Earl", artist: "Darts", genre: "70s" },
  { code: "1337", id: "PbSQf9RkVSU", title: "Walking in the Rain (Live)", artist: "The Ronettes", genre: "70s" },
  { code: "1338", id: "h9pUsAbObQU", title: "Never Ending Song of Love", artist: "The New Seekers", genre: "70s" },
  { code: "1339", id: "Tk0MwkDZhKs", title: "Figaro", artist: "Brotherhood of Man", genre: "70s" },
  { code: "1340", id: "-DJXeglQgkc", title: "Higher and Higher", artist: "Rita Coolidge", genre: "70s" },
  { code: "1341", id: "vvFPlWh1yQY", title: "Northern Lights", artist: "Renaissance", genre: "70s" },
  { code: "1342", id: "Q2dq6pU4J80", title: "Zing! Went the Strings of My Heart", artist: "The Trammps", genre: "70s" },
  { code: "1343", id: "IB5rNRSq7Uw", title: "Picture of You", artist: "Joe Brown, Vicki Brown & The Bruvvers", genre: "70s" },
  { code: "1344", id: "RJre-YHmLaI", title: "An Englishman in New York", artist: "Godley & Creme", genre: "70s" },
  { code: "1345", id: "I9SDEKlCCqE", title: "A Taste of Aggro", artist: "The Barron Knights", genre: "70s" },
  { code: "1346", id: "LaW5CzEtJOk", title: "Light My Fire", artist: "Amii Stewart", genre: "70s" },
  { code: "1347", id: "L4CcgblWC8k", title: "One Bad Apple", artist: "The Osmonds", genre: "70s" },
  { code: "1348", id: "1P0xVkOi-x8", title: "The Bad Old Days", artist: "Co-Co", genre: "70s" },
  { code: "1349", id: "6nimS21HiUo", title: "Daddy Cool", artist: "Darts", genre: "70s" },
  { code: "1350", id: "cVnUerDy3JQ", title: "Dear John", artist: "Teach-In", genre: "70s" },
  { code: "1351", id: "C_hPeGniLcs", title: "Matchstalk Men and Matchstalk Cats and Dogs", artist: "Ken Dodd", genre: "70s" },
  { code: "1352", id: "5ZnQQF7ucdM", title: "Little Does She Know", artist: "Kursaal Flyers", genre: "70s" },
  { code: "1353", id: "V7MOUefPxqc", title: "You Really Got Me", artist: "The Kinks", genre: "70s" },
  { code: "1354", id: "CCWAGpChSRI", title: "The Pushbike Song", artist: "The Mixtures", genre: "70s" },
  { code: "1355", id: "caDlnvqZCh0", title: "Forget About You", artist: "The Motors", genre: "70s" },
  { code: "1356", id: "wAXFkUaQoAs", title: "I Think I Love You", artist: "The Partridge Family", genre: "70s" },
  { code: "1357", id: "dldJCeZjcBo", title: "Luton Airport", artist: "Cats U.K.", genre: "70s" },
  { code: "1358", id: "X50KJp-oq9M", title: "January", artist: "Pilot", genre: "70s" },
  { code: "1359", id: "9p3sVCS0mz4", title: "Layla", artist: "Derek and the Dominos", genre: "70s" },
  { code: "1360", id: "2A2jwejaQGc", title: "Ma! He's Making Eyes at Me", artist: "Lena Zavaroni", genre: "70s" },
  { code: "1361", id: "fnb0Fn1_iDc", title: "Leap Up and Down (Wave Your Knickers in the Air)", artist: "St. Cecilia", genre: "70s" },
  { code: "1362", id: "MNkYZ91d8Lc", title: "5 O'Clock in the Morning", artist: "Godley & Creme", genre: "70s" },
  { code: "1363", id: "PZDwf_y_liA", title: "Boy Oh Boy", artist: "Racey", genre: "70s" },
  { code: "1364", id: "b4QzUkcwD4k", title: "I Can See Clearly Now", artist: "Johnny Nash", genre: "70s" },
  { code: "1365", id: "7XM5lMWpt18", title: "Hurt", artist: "The Manhattans", genre: "70s" },
  { code: "1366", id: "fzXR9DqXMi4", title: "The Robots (Live)", artist: "Kraftwerk", genre: "70s" },
  { code: "1367", id: "pFQtNgytSZk", title: "Come Back My Love", artist: "Darts", genre: "70s" },
  { code: "1368", id: "WD5PA44qUyk", title: "You're the Greatest Lover", artist: "Luv'", genre: "70s" },
  { code: "1369", id: "0HSdA5iUa18", title: "One Fine Day", artist: "Rita Coolidge", genre: "70s" },
  { code: "1370", id: "C4ER2afe1jY", title: "On My Radio", artist: "The Selecter", genre: "70s" },
  { code: "1371", id: "RSWALhr9byw", title: "The Night They Drove Old Dixie Down", artist: "Joan Baez", genre: "70s" },
  { code: "1372", id: "S61cI-E24a4", title: "Sweet Sweet Loretta", artist: "The DeFranco Family", genre: "70s" },
  { code: "1373", id: "WL9lg3dDgQo", title: "Wiggle That Wotsit", artist: "The Hollies", genre: "70s" },
  { code: "1500", id: "djV11Xbc914", title: "Take On Me", artist: "a-ha", genre: "80s" },
  { code: "1501", id: "btPJPFnesV4", title: "Eye of the Tiger", artist: "Survivor", genre: "80s" },
  { code: "1502", id: "PIb6AZdTr-A", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", genre: "80s" },
  { code: "1503", id: "Zi_XLOBDo_Y", title: "Billie Jean", artist: "Michael Jackson", genre: "80s" },
  { code: "1504", id: "sOnqjkJTMaA", title: "Thriller", artist: "Michael Jackson", genre: "80s" },
  { code: "1505", id: "1LwaYHkNXdQ", title: "Edge of Seventeen", artist: "Stevie Nicks", genre: "80s" },
  { code: "1506", id: "-qvTFnLwWOM", title: "Automatic", artist: "The Pointer Sisters", genre: "80s" },
  { code: "1507", id: "rXs9MXrHxVE", title: "Hit Me With Your Best Shot", artist: "Pat Benatar", genre: "80s" },
  { code: "1508", id: "2AilA-M6N5U", title: "Love Is A Long Road", artist: "Tom Petty & The Heartbreakers", genre: "80s" },
  { code: "1509", id: "wIiVp3poe2c", title: "The Power Of Love", artist: "Huey Lewis & The News", genre: "80s" },
  { code: "1510", id: "qGBohd0V2Mo", title: "Video Killed The Radio Star", artist: "The Buggles", genre: "80s" },
  { code: "1511", id: "valVixMpzQY", title: "One Way Or Another", artist: "Blondie", genre: "80s" },
  { code: "1512", id: "SVOuYquXuuc", title: "Owner of a Lonely Heart", artist: "Yes", genre: "80s" },
  { code: "1513", id: "aGCdLKXNF3w", title: "Everybody Wants To Rule The World", artist: "Tears For Fears", genre: "80s" },
  { code: "1514", id: "3wxyN3z9PL4", title: "Nothing's Gonna Stop Us Now", artist: "Starship", genre: "80s" },
  { code: "1515", id: "RP0_8J7uxhs", title: "Self Control", artist: "Laura Branigan", genre: "80s" },
  { code: "1516", id: "eH3giaIzONA", title: "I Wanna Dance With Somebody (Who Loves Me)", artist: "Whitney Houston", genre: "80s" },
  { code: "1517", id: "oGpFcHTxjZs", title: "What's Love Got To Do With It", artist: "Tina Turner", genre: "80s" },
  { code: "1518", id: "52iW3lcpK5M", title: "Into The Groove", artist: "Madonna", genre: "80s" },
  { code: "1519", id: "pIgZ7gMze7A", title: "Wake Me Up Before You Go-Go", artist: "Wham!", genre: "80s" },
  { code: "1520", id: "79fzeNUqQbQ", title: "Like A Prayer", artist: "Madonna", genre: "80s" },
  { code: "1521", id: "r3Pr1_v7hsw", title: "I Want To Know What Love Is", artist: "Foreigner", genre: "80s" },
  { code: "1522", id: "f4Mc-NYPHaQ", title: "I Want To Break Free", artist: "Queen", genre: "80s" },
  { code: "1523", id: "zpzdgmqIHOQ", title: "La Isla Bonita", artist: "Madonna", genre: "80s" },
  { code: "1524", id: "YkADj0TPrJA", title: "In The Air Tonight", artist: "Phil Collins", genre: "80s" },
  { code: "1525", id: "FTQbiNvZqaY", title: "Africa", artist: "Toto", genre: "80s" },
  { code: "1526", id: "oRdxUFDoQe0", title: "Beat It", artist: "Michael Jackson", genre: "80s" },
  { code: "1527", id: "uPudE8nDog0", title: "Don't You Want Me", artist: "The Human League", genre: "80s" },
  { code: "1528", id: "6p-lDYPR2P8", title: "Material Girl", artist: "Madonna", genre: "80s" },
  { code: "1529", id: "OMOGaugKpzs", title: "Every Breath You Take", artist: "The Police", genre: "80s" },
  { code: "1530", id: "TvnYmWpD_T8", title: "Purple Rain", artist: "Prince", genre: "80s" },
  { code: "1531", id: "r0qBaBb1Y-U", title: "Sussudio", artist: "Phil Collins", genre: "80s" },
  { code: "1532", id: "oJL-lCzEXgI", title: "Hungry like the Wolf", artist: "Duran Duran", genre: "80s" },
  { code: "1533", id: "VbD_kBJc_gI", title: "Let's Dance", artist: "David Bowie", genre: "80s" },
  { code: "1534", id: "a01QQZyl-_I", title: "Under Pressure", artist: "Queen and David Bowie", genre: "80s" },
  { code: "1535", id: "UG3VcCAlUgE", title: "When Doves Cry", artist: "Prince and the Revolution", genre: "80s" },
  { code: "1536", id: "2ySLmwsfP4Q", title: "Stay the Night", artist: "Benjamin Orr", genre: "80s" },
  { code: "1537", id: "BNirQXe8HOA", title: "Ain't Nobody", artist: "Rufus and Chaka Khan", genre: "80s" },
  { code: "1538", id: "opRRax4ph3E", title: "Dancing In The Street", artist: "David Bowie & Mick Jagger", genre: "80s" },
  { code: "1539", id: "UJ1tBVtYOBc", title: "I Can't Wait", artist: "Nu Shooz", genre: "80s" },
  { code: "1540", id: "9GMjH1nR0ds", title: "Blue Monday 88", artist: "New Order", genre: "80s" },
  { code: "1541", id: "UbxUSsFXYo4", title: "9 To 5", artist: "Dolly Parton", genre: "80s" },
  { code: "1542", id: "_aCAZNcTVeo", title: "Hard Habit To Break", artist: "Chicago", genre: "80s" },
  { code: "1543", id: "wp43OdtAAkM", title: "Running Up That Hill", artist: "Kate Bush", genre: "80s" },
  { code: "1544", id: "yQHhqDRn4_c", title: "Glory of Love", artist: "Peter Cetera", genre: "80s" },
  { code: "1545", id: "WGU_4-5RaxU", title: "Heart Of Glass", artist: "Blondie", genre: "80s" },
  { code: "1546", id: "cFH5JgyZK1I", title: "It's My Life", artist: "Talk Talk", genre: "80s" },
  { code: "1547", id: "_6FBfAQ-NDE", title: "Just Can't Get Enough", artist: "Depeche Mode", genre: "80s" },
  { code: "1548", id: "FIF7wKJb2iU", title: "Give Me The Night", artist: "George Benson", genre: "80s" },
  { code: "1549", id: "GuJQSAiODqI", title: "Vogue", artist: "Madonna", genre: "80s" },
  { code: "1550", id: "YF1R0hc5Q2I", title: "Everywhere", artist: "Fleetwood Mac", genre: "80s" },
  { code: "1551", id: "iWa-6g-TbgI", title: "Party All the Time", artist: "Eddie Murphy", genre: "80s" },
  { code: "1552", id: "6Cs3Pvmmv0E", title: "Faith", artist: "George Michael", genre: "80s" },
  { code: "1553", id: "m3-hY-hlhBg", title: "How Will I Know", artist: "Whitney Houston", genre: "80s" },
  { code: "1554", id: "52FFFWAPZpk", title: "Pour some sugar on me", artist: "Def Leppard", genre: "80s" },
  { code: "1555", id: "53LZ0-m-8Vg", title: "California Girls", artist: "David Lee Roth", genre: "80s" },
  { code: "1556", id: "rblt2EtFfC4", title: "1999", artist: "Prince", genre: "80s" },
  { code: "1557", id: "Fb2q141rMNE", title: "This Must Be the Place (Naïve Melody)", artist: "Talking Heads", genre: "80s" },
  { code: "1558", id: "AIBv2GEnXlc", title: "Never Tear Us Apart", artist: "INXS", genre: "80s" },
  { code: "1559", id: "qeMFqkcPYcg", title: "Sweet Dreams (Are Made Of This)", artist: "Eurythmics, Annie Lennox, Dave Stewart", genre: "80s" },
  { code: "1560", id: "H9tEvfIsDyo", title: "Kiss", artist: "Prince and the Revolution", genre: "80s" },
  { code: "1561", id: "gwS9BIqbffU", title: "Stand Back", artist: "Stevie Nicks", genre: "80s" },
  { code: "1562", id: "5IsSpAOD6K8", title: "Once in a Lifetime", artist: "Talking Heads", genre: "80s" },
  { code: "1563", id: "rkpG4XApJ28", title: "Too Shy", artist: "Kajagoogoo", genre: "80s" },
  { code: "1564", id: "WyF8RHM1OCg", title: "Here I Go Again '87", artist: "Whitesnake", genre: "80s" },
  { code: "1565", id: "v0KpfrJE4zw", title: "Little Red Corvette", artist: "Prince", genre: "80s" },
  { code: "1566", id: "p3j2NYZ8FKs", title: "West End Girls", artist: "Pet Shop Boys", genre: "80s" },
  { code: "1567", id: "ccenFp_3kq8", title: "I Can't Go For That (No Can Do)", artist: "Daryl Hall & John Oates", genre: "80s" },
  { code: "1568", id: "kd9TlGDZGkI", title: "Walk Of Life", artist: "Dire Straits", genre: "80s" },
  { code: "1569", id: "P0FKzPfsxA4", title: "Every Little Step", artist: "Bobby Brown", genre: "80s" },
  { code: "1570", id: "pHCdS7O248g", title: "Rapture", artist: "Blondie", genre: "80s" },
  { code: "1571", id: "9b4F_ppjnKU", title: "Seven Wonders", artist: "Fleetwood Mac", genre: "80s" },
  { code: "1572", id: "6Zqtl8azCs8", title: "The Glamorous Life", artist: "Sheila E.", genre: "80s" },
  { code: "1573", id: "aXJhDltzYVQ", title: "Let's Go Crazy", artist: "Prince and the Revolution", genre: "80s" },
  { code: "1574", id: "6tatKFXlYiY", title: "When The Children Cry", artist: "White Lion", genre: "80s" },
  { code: "1575", id: "nNEb2k_EmMg", title: "Gloria", artist: "Laura Branigan", genre: "80s" },
  { code: "1576", id: "uq-gYOrU8bA", title: "You Can Call Me Al", artist: "Paul Simon", genre: "80s" },
  { code: "1577", id: "Lrle0x_DHBM", title: "Let's Groove", artist: "Earth, Wind & Fire", genre: "80s" },
  { code: "1578", id: "4N1iwQxiHrs", title: "Your Love", artist: "The Outfield", genre: "80s" },
  { code: "1579", id: "MFmNWLTMSXY", title: "The Walk", artist: "The Time", genre: "80s" },
  { code: "1580", id: "SECVGN4Bsgg", title: "Who Can It Be Now?", artist: "Men At Work", genre: "80s" },
  { code: "1581", id: "uxX2gA18grk", title: "Caribbean Queen (No More Love on the Run)", artist: "Billy Ocean", genre: "80s" },
  { code: "1582", id: "R5RwQ6d35wA", title: "Cool", artist: "The Time", genre: "80s" },
  { code: "1583", id: "9SOryJvTAGs", title: "Love Shack", artist: "The B-52's", genre: "80s" },
  { code: "1584", id: "rkdhhEjX-I0", title: "Just A Gigolo / I Ain't Got Nobody", artist: "David Lee Roth", genre: "80s" },
  { code: "1585", id: "vCadcBR95oU", title: "Push It", artist: "Salt-N-Pepa", genre: "80s" },
  { code: "1586", id: "l9ml3nyww80", title: "Cruel Summer", artist: "Bananarama", genre: "80s" },
  { code: "1587", id: "OJWJE0x7T4Q", title: "Sledgehammer", artist: "Peter Gabriel", genre: "80s" },
  { code: "1588", id: "DnuKxTff55s", title: "Love Will Show Us How", artist: "Christine McVie", genre: "80s" },
  { code: "1589", id: "aCWCF19nUhA", title: "Genius Of Love", artist: "Tom Tom Club", genre: "80s" },
  { code: "1590", id: "FtovFI8etOg", title: "New Frontier", artist: "Donald Fagen", genre: "80s" },
  { code: "1591", id: "F9Y9flntJxE", title: "Ice Cream Castles", artist: "The Time", genre: "80s" },
  { code: "1592", id: "ThHz9wlBeLU", title: "Lucky Star", artist: "Madonna", genre: "80s" },
  { code: "1593", id: "zQ41hqlV0Kk", title: "Young Turks", artist: "Rod Stewart", genre: "80s" },
  { code: "1594", id: "9gbQVj4MR3M", title: "I Keep Forgettin' (Every Time You're Near)", artist: "Michael McDonald", genre: "80s" },
  { code: "1595", id: "129kuDCQtHs", title: "Dancing In the Dark", artist: "Bruce Springsteen", genre: "80s" },
  { code: "1596", id: "LGD9i718kBU", title: "Love My Way", artist: "The Psychedelic Furs", genre: "80s" },
  { code: "1597", id: "3xXPlTaDj84", title: "No Lookin' Back", artist: "Michael McDonald", genre: "80s" },
  { code: "1598", id: "JkRKT6T0QLg", title: "Easy Lover", artist: "Philip Bailey, Phil Collins", genre: "80s" },
  { code: "1599", id: "Xg1t-fqhbf8", title: "Got A Hold On Me", artist: "Christine McVie", genre: "80s" },
  { code: "1600", id: "CdqoNKCCt7A", title: "Don't You (Forget About Me)", artist: "Simple Minds", genre: "80s" },
  { code: "1601", id: "SwYN7mTi6HM", title: "Jump", artist: "Van Halen", genre: "80s" },
  { code: "1602", id: "P7Tcggo45TQ", title: "Bang The Drum All Day", artist: "Todd Rundgren", genre: "80s" },
  { code: "1603", id: "EPOIS5taqA8", title: "Bette Davis Eyes", artist: "Kim Carnes", genre: "80s" },
  { code: "1604", id: "mwgg1Pu6cNg", title: "Gypsy", artist: "Fleetwood Mac", genre: "80s" },
  { code: "1605", id: "Ruc7AFi908g", title: "Change Myself", artist: "Todd Rundgren", genre: "80s" },
  { code: "1606", id: "7wRHBLwpASw", title: "Sharp Dressed Man", artist: "ZZ Top", genre: "80s" },
  { code: "1607", id: "3dOx510kyOs", title: "You Might Think", artist: "The Cars", genre: "80s" },
  { code: "1608", id: "bJ9r8LMU9bQ", title: "Rock the Casbah", artist: "The Clash", genre: "80s" },
  { code: "1609", id: "aENX1Sf3fgQ", title: "Every Little Thing She Does Is Magic", artist: "The Police", genre: "80s" },
  { code: "1610", id: "alSUZP0_7o4", title: "I Gotta Try", artist: "Michael McDonald", genre: "80s" },
  { code: "1611", id: "l7vRSu_wsNc", title: "Raspberry Beret", artist: "Prince and the Revolution", genre: "80s" },
  { code: "1612", id: "RZUq6N7Gx1c", title: "Cool It Now", artist: "New Edition", genre: "80s" },
  { code: "1613", id: "JIrm0dHbCDU", title: "Strangelove", artist: "Depeche Mode", genre: "80s" },
  { code: "1614", id: "uvvdUjTjcKc", title: "Tonight I'm Yours", artist: "Rod Stewart", genre: "80s" },
  { code: "1615", id: "HVn-DMijdxY", title: "Time Heals", artist: "Todd Rundgren", genre: "80s" },
  { code: "1616", id: "rY0WxgSXdEE", title: "Another One Bites the Dust", artist: "Queen", genre: "80s" },
  { code: "1617", id: "eBShN8qT4lk", title: "(You Gotta) Fight For Your Right (To Party)", artist: "Beastie Boys", genre: "80s" },
  { code: "1618", id: "fuKDBPw8wQA", title: "Panama", artist: "Van Halen", genre: "80s" },
  { code: "1619", id: "JHYIGy1dyd8", title: "One Thing Leads To Another", artist: "The Fixx", genre: "80s" },
  { code: "1620", id: "cJRP3LRcUFg", title: "This Charming Man", artist: "The Smiths", genre: "80s" },
  { code: "1621", id: "s__rX_WL100", title: "Like A Virgin", artist: "Madonna", genre: "80s" },
  { code: "1622", id: "uCGD9dT12C0", title: "Little Lies", artist: "Fleetwood Mac", genre: "80s" },
  { code: "1623", id: "J9gKyRmic20", title: "Don't Dream It's Over", artist: "Crowded House", genre: "80s" },
  { code: "1624", id: "9OFpfTd0EIs", title: "Eyes Without A Face", artist: "Billy Idol", genre: "80s" },
  { code: "1625", id: "H5i7j0VhEHw", title: "Stop Draggin' My Heart Around", artist: "Stevie Nicks", genre: "80s" },
  { code: "1626", id: "Bx51eegLTY8", title: "Take My Breath Away", artist: "Berlin", genre: "80s" },
  { code: "1627", id: "VdQY7BusJNU", title: "Time After Time", artist: "Cyndi Lauper", genre: "80s" },
  { code: "1628", id: "x34icYC8zA0", title: "A Little Respect", artist: "Erasure", genre: "80s" },
  { code: "1629", id: "GsVcUzP_O_8", title: "Express Yourself", artist: "Madonna", genre: "80s" },
  { code: "1630", id: "wDe60CbIagg", title: "Always On My Mind", artist: "Pet Shop Boys", genre: "80s" },
  { code: "1631", id: "Ae829mFAGGE", title: "Gimme All Your Lovin'", artist: "ZZ Top", genre: "80s" },
  { code: "1632", id: "snILjFUkk_A", title: "Never Let Me Down Again", artist: "Depeche Mode", genre: "80s" },
  { code: "1633", id: "phOW-CZJWT0", title: "It Takes Two", artist: "Rob Base & DJ EZ Rock", genre: "80s" },
  { code: "1634", id: "oXA6CLTDekw", title: "Our House", artist: "Madness", genre: "80s" },
  { code: "1635", id: "EErSKhC0CZs", title: "You Make My Dreams", artist: "Daryl Hall & John Oates", genre: "80s" },
  { code: "1636", id: "nKhN1t_7PEY", title: "Broken Wings", artist: "Mr. Mister", genre: "80s" },
  { code: "1637", id: "rjlSiASsUIs", title: "Sexual Healing", artist: "Marvin Gaye", genre: "80s" },
  { code: "1638", id: "rSaC-YbSDpo", title: "Borderline", artist: "Madonna", genre: "80s" },
  { code: "1639", id: "2WN0T-Ee3q4", title: "Never Ending Story", artist: "Limahl", genre: "80s" },
  { code: "1640", id: "RY7S6EgSlCI", title: "Overkill", artist: "Men At Work", genre: "80s" },
  { code: "1641", id: "yCC_b5WHLX0", title: "Listen To Your Heart", artist: "Roxette", genre: "80s" },
  { code: "1642", id: "t1TcDHrkQYg", title: "Forever Young", artist: "Alphaville", genre: "80s" },
  { code: "1643", id: "Xq3hEMUeBGQ", title: "Centerfield", artist: "John Fogerty", genre: "80s" },
  { code: "1644", id: "_71w4UA2Oxo", title: "Got My Mind Set On You", artist: "George Harrison", genre: "80s" },
  { code: "1645", id: "eUDcTLaWJuo", title: "Legs", artist: "ZZ Top", genre: "80s" },
  { code: "1646", id: "HivQqTtiHVw", title: "Modern Love", artist: "David Bowie", genre: "80s" },
  { code: "1647", id: "XfR9iY5y94s", title: "Down Under", artist: "Men At Work", genre: "80s" },
  { code: "1648", id: "r0qDBYiOBrc", title: "Who's That Girl", artist: "Madonna", genre: "80s" },
  { code: "1649", id: "Ye7FKc1JQe4", title: "Shout", artist: "Tears For Fears", genre: "80s" },
  { code: "1650", id: "yRYFKcMa_Ek", title: "Maneater", artist: "Daryl Hall & John Oates", genre: "80s" },
  { code: "1651", id: "k9olaIio3l8", title: "Higher Love", artist: "Steve Winwood", genre: "80s" },
  { code: "1652", id: "xuZA6qiJVfU", title: "Drive", artist: "The Cars", genre: "80s" },
  { code: "1653", id: "qmOLtTGvsbM", title: "Rosanna", artist: "Toto", genre: "80s" },
  { code: "1654", id: "GC5E8ie2pdM", title: "The Best", artist: "Tina Turner", genre: "80s" },
  { code: "1655", id: "tbNlMtqrYS0", title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers", genre: "80s" },
  { code: "1656", id: "dx7vNdAb5e4", title: "St. Elmo's Fire (Man In Motion)", artist: "John Parr", genre: "80s" },
  { code: "1657", id: "dsUXAEzaC3Q", title: "Bad", artist: "Michael Jackson", genre: "80s" },
  { code: "1658", id: "ntG50eXbBtc", title: "Gold", artist: "Spandau Ballet", genre: "80s" },
  { code: "1659", id: "kOnde5c7OG8", title: "More Than This", artist: "Roxy Music", genre: "80s" },
  { code: "1660", id: "pufec0Hps00", title: "Burning Up", artist: "Madonna", genre: "80s" },
  { code: "1661", id: "cVikZ8Oe_XA", title: "Rock Me Amadeus", artist: "Falco", genre: "80s" },
  { code: "1662", id: "Yq7FKO5DlV0", title: "Land of Confusion", artist: "Genesis", genre: "80s" },
  { code: "1663", id: "siwpn14IE7E", title: "Danger Zone", artist: "Kenny Loggins", genre: "80s" },
  { code: "1664", id: "h_D3VFfhvs4", title: "Smooth Criminal", artist: "Michael Jackson", genre: "80s" },
  { code: "1665", id: "4B_UYYPb-Gk", title: "Walk This Way ft. Aerosmith", artist: "RUN DMC", genre: "80s" },
  { code: "1666", id: "6M4_Ommfvv0", title: "Hot For Teacher", artist: "Van Halen", genre: "80s" },
  { code: "1667", id: "EPhWR4d3FJQ", title: "Born in the U.S.A.", artist: "Bruce Springsteen", genre: "80s" },
  { code: "1668", id: "FrkEDe6Ljqs", title: "Nightshift", artist: "Commodores", genre: "80s" },
  { code: "1669", id: "nqAvFx3NxUM", title: "All Night Long (All Night)", artist: "Lionel Richie", genre: "80s" },
  { code: "1670", id: "XBZUz4C6kqk", title: "King Of Wishful Thinking", artist: "Go West", genre: "80s" },
  { code: "1671", id: "iPUmE-tne5U", title: "Walking On Sunshine", artist: "Katrina & The Waves", genre: "80s" },
  { code: "1672", id: "Cv6tuzHUuuk", title: "Walk Like an Egyptian", artist: "The Bangles", genre: "80s" },
  { code: "1673", id: "LlVI7ZNiFlI", title: "The Look", artist: "Roxette", genre: "80s" },
  { code: "1674", id: "JmcA9LIIXWw", title: "Karma Chameleon", artist: "Culture Club", genre: "80s" },
  { code: "1675", id: "M3cd0zxd7EU", title: "Playing with the Boys", artist: "Kenny Loggins", genre: "80s" },
  { code: "1676", id: "nTizYn3-QN0", title: "Rio", artist: "Duran Duran", genre: "80s" },
  { code: "1677", id: "G333Is7VPOg", title: "Papa Don't Preach", artist: "Madonna", genre: "80s" },
  { code: "1678", id: "StKVS0eI85I", title: "Call me", artist: "Blondie", genre: "80s" },
  { code: "1679", id: "Tc1IphRx1pk", title: "Pull Up To The Bumper", artist: "Grace Jones", genre: "80s" },
  { code: "1680", id: "jpmiZ7zsHXY", title: "Invisible Touch", artist: "Genesis", genre: "80s" },
  { code: "1681", id: "cAQSZhazYk8", title: "Rhythm Of The Night", artist: "DeBarge", genre: "80s" },
  { code: "1682", id: "Z9_CdgnUQL8", title: "That Girl", artist: "Christopher Cross", genre: "80s" },
  { code: "1683", id: "bpA_5a0miWk", title: "Avalon", artist: "Roxy Music", genre: "80s" },
  { code: "1684", id: "3h-6tpuBuHs", title: "Club Boy", artist: "Bianca", genre: "80s" },
  { code: "1685", id: "pcXzLjWangw", title: "Lost In The Parade", artist: "Michael McDonald", genre: "80s" },
  { code: "1686", id: "sEJwCQ7MHR0", title: "Along Comes A Woman", artist: "Chicago", genre: "80s" },
  { code: "1687", id: "A9YCg1uQ0ow", title: "25 or 6 to 4", artist: "Chicago", genre: "80s" },
  { code: "1688", id: "mUg5aEy-8CQ", title: "Nothing's Gonna Change My Love For You", artist: "Glenn Medeiros", genre: "80s" },
  { code: "1689", id: "SGyOaCXr8Lw", title: "Start Me Up", artist: "The Rolling Stones", genre: "80s" },
  { code: "1690", id: "nAkMTu6q2pY", title: "Harlem Shuffle", artist: "The Rolling Stones", genre: "80s" },
  { code: "1691", id: "FZ4jMSCBswY", title: "Double Dutch", artist: "Malcolm McLaren", genre: "80s" },
  { code: "1800", id: "XFkzRNyygfk", title: "Creep", artist: "Radiohead", genre: "90s" },
  { code: "1801", id: "6NXnxTNIWkc", title: "What's Up?", artist: "4 Non Blondes", genre: "90s" },
  { code: "1802", id: "Y0pdQU87dc8", title: "(Everything I Do) I Do It for You", artist: "Bryan Adams", genre: "90s" },
  { code: "1803", id: "QNJL6nfu__Q", title: "They Don't Care About Us", artist: "Michael Jackson", genre: "90s" },
  { code: "1804", id: "6Ejga4kJUts", title: "Zombie", artist: "The Cranberries", genre: "90s" },
  { code: "1805", id: "3JWTaaS7LdU", title: "I Will Always Love You", artist: "Whitney Houston", genre: "90s" },
  { code: "1806", id: "HyrWd_gfQNQ", title: "Nothing Else Matters", artist: "Metallica", genre: "90s" },
  { code: "1807", id: "n4RjJKxsamQ", title: "Wind of Change", artist: "Scorpions", genre: "90s" },
  { code: "1808", id: "C-u5WLJ9Yk4", title: "...Baby One More Time", artist: "Britney Spears", genre: "90s" },
  { code: "1809", id: "oKOtzIo-uYw", title: "Killing Me Softly with His Song", artist: "Fugees", genre: "90s" },
  { code: "1810", id: "HEXWRTEbj1I", title: "What Is Love", artist: "Haddaway", genre: "90s" },
  { code: "1811", id: "TR3Vdo5etCQ", title: "Don't Speak", artist: "No Doubt", genre: "90s" },
  { code: "1812", id: "xwtdhWltSIg", title: "Losing My Religion", artist: "R.E.M.", genre: "90s" },
  { code: "1813", id: "9BMwcO6_hyA", title: "Always", artist: "Bon Jovi", genre: "90s" },
  { code: "1814", id: "FxYw0XPEoKE", title: "I Have Nothing", artist: "Whitney Houston", genre: "90s" },
  { code: "1815", id: "vabnZ9-ex7o", title: "Come as You Are", artist: "Nirvana", genre: "90s" },
  { code: "1816", id: "7iNbnineUCI", title: "The Kids Aren't Alright", artist: "The Offspring", genre: "90s" },
  { code: "1817", id: "XAi3VTSdTxU", title: "Earth Song", artist: "Michael Jackson", genre: "90s" },
  { code: "1818", id: "CD-E-LDc384", title: "Enter Sandman", artist: "Metallica", genre: "90s" },
  { code: "1819", id: "qSIOp_K5GMw", title: "The Boy Is Mine", artist: "Brandy & Monica", genre: "90s" },
  { code: "1820", id: "d73tiBBzvFM", title: "All That She Wants", artist: "Ace of Base", genre: "90s" },
  { code: "1821", id: "G6Kspj3OO0s", title: "Linger", artist: "The Cranberries", genre: "90s" },
  { code: "1822", id: "HWjCStB6k4o", title: "Happy Nation", artist: "Ace of Base", genre: "90s" },
  { code: "1823", id: "kIDWgqDBNXA", title: "Genie in a Bottle", artist: "Christina Aguilera", genre: "90s" },
  { code: "1824", id: "EScLmWJs82I", title: "Coco Jamboo", artist: "Mr. President", genre: "90s" },
  { code: "1825", id: "mzJj5-lubeM", title: "Scar Tissue", artist: "Red Hot Chili Peppers", genre: "90s" },
  { code: "1826", id: "ImKY6TZEyrI", title: "Fade Into You", artist: "Mazzy Star", genre: "90s" },
  { code: "1827", id: "JkK8g6FMEXE", title: "I Don't Want to Miss a Thing", artist: "Aerosmith", genre: "90s" },
  { code: "1828", id: "1TO48Cnl66w", title: "Thank You", artist: "Dido", genre: "90s" },
  { code: "1829", id: "fregObNcHC8", title: "The Man Who Sold the World (MTV Unplugged)", artist: "Nirvana", genre: "90s" },
  { code: "1830", id: "nPLV7lGbmT4", title: "Maria Maria ft. The Product G&B", artist: "Santana", genre: "90s" },
  { code: "1831", id: "zRIbf6JqkNc", title: "Don't Cry", artist: "Guns N' Roses", genre: "90s" },
  { code: "1832", id: "YP3W-E0OamU", title: "Black or White", artist: "Michael Jackson", genre: "90s" },
  { code: "1833", id: "UrIiLvg58SY", title: "More Than Words", artist: "Extreme", genre: "90s" },
  { code: "1834", id: "FrLequ6dUdM", title: "No Scrubs", artist: "TLC", genre: "90s" },
  { code: "1835", id: "ZJL4UGSbeFg", title: "Man! I Feel Like a Woman!", artist: "Shania Twain", genre: "90s" },
  { code: "1836", id: "jQY_QL_wvQU", title: "Will You Be There", artist: "Michael Jackson", genre: "90s" },
  { code: "1837", id: "SSbBvKaM6sk", title: "Song 2", artist: "Blur", genre: "90s" },
  { code: "1838", id: "BWf-eARnf6U", title: "Heal the World", artist: "Michael Jackson", genre: "90s" },
  { code: "1839", id: "0-EF60neguk", title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", genre: "90s" },
  { code: "1840", id: "p47fEXGabaY", title: "Livin' la Vida Loca", artist: "Ricky Martin", genre: "90s" },
  { code: "1841", id: "LKaXY4IdZ40", title: "When You Believe", artist: "Whitney Houston & Mariah Carey", genre: "90s" },
  { code: "1842", id: "C3lWwBslWqg", title: "Desert Rose", artist: "Sting", genre: "90s" },
  { code: "1843", id: "pAyKJAtDNCw", title: "You Are Not Alone", artist: "Michael Jackson", genre: "90s" },
  { code: "1844", id: "nZXRV4MezEw", title: "Believe", artist: "Cher", genre: "90s" },
  { code: "1845", id: "gJLIiF15wjQ", title: "Wannabe", artist: "Spice Girls", genre: "90s" },
  { code: "1846", id: "N9kdHXrJYF8", title: "Stand by Me", artist: "Oasis", genre: "90s" },
  { code: "1847", id: "ZMtf_ouMTHw", title: "Mr. Vain", artist: "Culture Beat", genre: "90s" },
  { code: "1848", id: "N0VdRLdg2ng", title: "California Love ft. Dr. Dre and Roger Troutman", artist: "2Pac", genre: "90s" },
  { code: "1849", id: "qgaRVvAKoqQ", title: "Black", artist: "Pearl Jam", genre: "90s" },
  { code: "1850", id: "NvR60Wg9R7Q", title: "Bed of Roses", artist: "Bon Jovi", genre: "90s" },
  { code: "1851", id: "r8OipmKFDeM", title: "Don't Look Back in Anger", artist: "Oasis", genre: "90s" },
  { code: "1852", id: "NUTGr5t3MoY", title: "Basket Case", artist: "Green Day", genre: "90s" },
  { code: "1853", id: "v45F0YesdZM", title: "Kiss Me", artist: "Sixpence None the Richer", genre: "90s" },
  { code: "1854", id: "EK_LN3XEcnw", title: "Mambo No. 5 (A Little Bit of...)", artist: "Lou Bega", genre: "90s" },
  { code: "1855", id: "Z193UHZnhB4", title: "Just Another Day", artist: "Jon Secada", genre: "90s" },
  { code: "1856", id: "Hy8kmNEo1i8", title: "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)", artist: "Scatman John", genre: "90s" },
  { code: "1857", id: "p2Rch6WvPJE", title: "Un-Break My Heart", artist: "Toni Braxton", genre: "90s" },
  { code: "1858", id: "3mbBbFH9fAg", title: "Black Hole Sun", artist: "Soundgarden", genre: "90s" },
  { code: "1859", id: "w6FEGa4azy8", title: "Dreams", artist: "The Cranberries", genre: "90s" },
  { code: "1860", id: "3SoYkCAzMBk", title: "Can We Talk", artist: "Tevin Campbell", genre: "90s" },
  { code: "1861", id: "ixqOgtNERAQ", title: "Bailamos", artist: "Enrique Iglesias", genre: "90s" },
  { code: "1862", id: "6Whgn_iE5uc", title: "Smooth ft. Rob Thomas", artist: "Santana", genre: "90s" },
  { code: "1863", id: "xat1GVnl8-k", title: "The Bad Touch", artist: "Bloodhound Gang", genre: "90s" },
  { code: "1864", id: "VV1XWJN3nJo", title: "Torn", artist: "Natalie Imbruglia", genre: "90s" },
  { code: "1865", id: "3C8bvYlqy9A", title: "Think About the Way", artist: "ICE MC", genre: "90s" },
  { code: "1866", id: "T6QKqFPRZSA", title: "Doo Wop (That Thing)", artist: "Lauryn Hill", genre: "90s" },
  { code: "1867", id: "GLvohMXgcBo", title: "Under the Bridge", artist: "Red Hot Chili Peppers", genre: "90s" },
  { code: "1868", id: "NMNgbISmF4I", title: "Crazy", artist: "Aerosmith", genre: "90s" },
  { code: "1869", id: "uB1D9wWxd2w", title: "Return of the Mack", artist: "Mark Morrison", genre: "90s" },
  { code: "1870", id: "DXvMT_mVbqw", title: "All My Life", artist: "K-Ci & JoJo", genre: "90s" },
  { code: "1871", id: "9X_ViIPA-Gc", title: "I'd Do Anything for Love (But I Won't Do That)", artist: "Meat Loaf", genre: "90s" },
  { code: "1872", id: "Pav2f4b-1ZE", title: "Another Night", artist: "Real McCoy", genre: "90s" },
  { code: "1873", id: "EzUX2jbBJAc", title: "Sweet Dreams", artist: "La Bouche", genre: "90s" },
  { code: "1874", id: "LfRNRymrv9k", title: "Always Be My Baby", artist: "Mariah Carey", genre: "90s" },
  { code: "1875", id: "97yYjrRv5hE", title: "Lift Your Head Up", artist: "Haddaway", genre: "90s" },
  { code: "1876", id: "_0JrmT3FjBE", title: "Everybody", artist: "DJ BoBo", genre: "90s" },
  { code: "1877", id: "is6gtilerPk", title: "I Want You Back", artist: "*NSYNC", genre: "90s" },
  { code: "1878", id: "NI6aOFI7hms", title: "Lovefool", artist: "The Cardigans", genre: "90s" },
  { code: "1879", id: "Jne9t8sHpUc", title: "Ironic", artist: "Alanis Morissette", genre: "90s" },
  { code: "1880", id: "zSmOvYzSeaQ", title: "Amazing", artist: "Aerosmith", genre: "90s" },
  { code: "1881", id: "IobNcpiwpSc", title: "When You Say Nothing at All", artist: "Ronan Keating", genre: "90s" },
  { code: "1882", id: "llyiQ4I-mcQ", title: "Boom, Boom, Boom, Boom!!", artist: "Vengaboys", genre: "90s" },
  { code: "1883", id: "SGK00Q7xx-s", title: "Blind", artist: "Korn", genre: "90s" },
  { code: "1884", id: "mOYZaiDZ7BM", title: "Cotton Eye Joe", artist: "Rednex", genre: "90s" },
  { code: "1885", id: "HaC0s-FP-r4", title: "Hole in My Soul", artist: "Aerosmith", genre: "90s" },
  { code: "1886", id: "aY2sBDPgOXU", title: "I Live My Life for You", artist: "Firehouse", genre: "90s" },
  { code: "1887", id: "c3_NntYhzV4", title: "Blood on the Dance Floor", artist: "Michael Jackson", genre: "90s" },
  { code: "1888", id: "Ps2Jc28tQrw", title: "Show Me Love", artist: "Robin S", genre: "90s" },
  { code: "1889", id: "WQnAxOQxQIU", title: "Truly Madly Deeply", artist: "Savage Garden", genre: "90s" },
  { code: "1890", id: "mGgMZpGYiy8", title: "Friday I'm in Love", artist: "The Cure", genre: "90s" },
  { code: "1891", id: "MfmYCM4CS8o", title: "Blaze of Glory", artist: "Jon Bon Jovi", genre: "90s" },
  { code: "1892", id: "LaTGrV58wec", title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory", genre: "90s" },
  { code: "1893", id: "-oqAU5VxFWs", title: "Mr. Jones", artist: "Counting Crows", genre: "90s" },
  { code: "1894", id: "XAa4kZ8Gnt4", title: "I Gotta Be", artist: "Jagged Edge", genre: "90s" },
  { code: "1895", id: "iqu132vTl5Y", title: "The Sign", artist: "Ace of Base", genre: "90s" },
  { code: "1896", id: "vGwIaL0jOUg", title: "Think Twice", artist: "Céline Dion", genre: "90s" },
  { code: "1897", id: "_ZcmuKsyvzg", title: "Tearin' Up My Heart", artist: "*NSYNC", genre: "90s" },
  { code: "1898", id: "NKMtZm2YuBE", title: "I'll Be Missing You ft. Faith Evans & 112", artist: "Puff Daddy", genre: "90s" },
  { code: "1899", id: "QtTR-_Klcq8", title: "Pretty Fly (for a White Guy)", artist: "The Offspring", genre: "90s" },
  { code: "1900", id: "FqIACCH20JU", title: "Ordinary World", artist: "Duran Duran", genre: "90s" },
  { code: "1901", id: "Oe9VB8t3m2w", title: "It's All Coming Back to Me Now", artist: "Céline Dion", genre: "90s" },
  { code: "1902", id: "MUuNDb-nm5M", title: "When a Man Loves a Woman", artist: "Michael Bolton", genre: "90s" },
  { code: "1903", id: "NHozn0YXAeE", title: "MMMBop", artist: "Hanson", genre: "90s" },
  { code: "1904", id: "Xh9Cp4rd7mI", title: "Ghosts", artist: "Michael Jackson", genre: "90s" },
  { code: "1905", id: "f8hT3oDDf6c", title: "Down in a Hole", artist: "Alice in Chains", genre: "90s" },
  { code: "1906", id: "i8dh9gDzmz8", title: "When I Come Around", artist: "Green Day", genre: "90s" },
  { code: "1907", id: "A-oh-tP6RvA", title: "Barely Breathing", artist: "Duncan Sheik", genre: "90s" },
  { code: "1908", id: "K0HSD_i2DvA", title: "Around the World", artist: "Daft Punk", genre: "90s" },
  { code: "1909", id: "pkcJEvMcnEg", title: "Lithium", artist: "Nirvana", genre: "90s" },
  { code: "1910", id: "iqIq4B1rgl4", title: "Mysterious Girl", artist: "Peter Andre", genre: "90s" },
  { code: "1911", id: "4aeETEoNfOg", title: "1979", artist: "The Smashing Pumpkins", genre: "90s" },
  { code: "1912", id: "L6-uJLteKek", title: "To Be with You", artist: "Mr. Big", genre: "90s" },
  { code: "1913", id: "kemivUKb4f4", title: "Buddy Holly", artist: "Weezer", genre: "90s" },
  { code: "1914", id: "lVL-zZnD3VU", title: "Your Woman", artist: "White Town", genre: "90s" },
  { code: "1915", id: "yjJL9DGU7Gg", title: "Interstate Love Song", artist: "Stone Temple Pilots", genre: "90s" },
  { code: "1916", id: "MH6TJU0qWoY", title: "Lucky Man", artist: "The Verve", genre: "90s" },
  { code: "1917", id: "LH-i8IvYIcg", title: "Why Don't You Get a Job?", artist: "The Offspring", genre: "90s" },
  { code: "1918", id: "Nntd2fgMUYw", title: "Save Tonight", artist: "Eagle-Eye Cherry", genre: "90s" },
  { code: "1919", id: "G_UXvcr22rM", title: "Would I Lie to You?", artist: "Charles & Eddie", genre: "90s" },
  { code: "1920", id: "4qQyUi4zfDs", title: "Glory Box", artist: "Portishead", genre: "90s" },
  { code: "1921", id: "99j0zLuNhi8", title: "With Arms Wide Open", artist: "Creed", genre: "90s" },
  { code: "1922", id: "EvuL5jyCHOw", title: "Fly Away", artist: "Lenny Kravitz", genre: "90s" },
  { code: "1923", id: "byQIPdHMpjc", title: "Achy Breaky Heart", artist: "Billy Ray Cyrus", genre: "90s" },
  { code: "1924", id: "J16lInLZRms", title: "Higher", artist: "Creed", genre: "90s" },
  { code: "1925", id: "LNBjMRvOB5M", title: "Go West", artist: "Pet Shop Boys", genre: "90s" },
  { code: "1926", id: "iBBqjGd3fHQ", title: "My Own Prison", artist: "Creed", genre: "90s" },
  { code: "1927", id: "NGrLb6W5YOM", title: "All by Myself", artist: "Céline Dion", genre: "90s" },
  { code: "1928", id: "FkDpwF6-QiA", title: "Love Takes Time", artist: "Mariah Carey", genre: "90s" },
  { code: "2000", id: "beINamVRGy4", title: "Semi-Charmed Life", artist: "Third Eye Blind", genre: "90s-rock" },
  { code: "2001", id: "T8Xb_7YDroQ", title: "Inside Out", artist: "Eve 6", genre: "90s-rock" },
  { code: "2002", id: "xCmA1uC0r9A", title: "Bullet with Butterfly Wings", artist: "The Smashing Pumpkins", genre: "90s-rock" },
  { code: "2003", id: "MS91knuzoOA", title: "Jeremy", artist: "Pearl Jam", genre: "90s-rock" },
  { code: "2004", id: "eBG7P-K-r1Y", title: "Everlong", artist: "Foo Fighters", genre: "90s-rock" },
  { code: "2005", id: "AEYN5w4T_aM", title: "Santeria", artist: "Sublime", genre: "90s-rock" },
  { code: "2006", id: "HAkHqYlqops", title: "Push", artist: "Matchbox Twenty", genre: "90s-rock" },
  { code: "2007", id: "Sfg6-4mBs6Y", title: "If You Could Only See", artist: "Tonic", genre: "90s-rock" },
  { code: "2008", id: "NdYWuo9OFAw", title: "Iris", artist: "Goo Goo Dolls", genre: "90s-rock" },
  { code: "2009", id: "hOllF3TgAsM", title: "Glycerine", artist: "Bush", genre: "90s-rock" },
  { code: "2010", id: "qA1nGPM9yHA", title: "What It's Like", artist: "Everlast", genre: "90s-rock" },
  { code: "2011", id: "xsJ4O-nSveg", title: "Lightning Crashes", artist: "Live", genre: "90s-rock" },
  { code: "2012", id: "v74yTy1UTuk", title: "Desperately Wanting", artist: "Better Than Ezra", genre: "90s-rock" },
  { code: "2013", id: "eu3EuWg2qNI", title: "Far Behind", artist: "Candlebox", genre: "90s-rock" },
  { code: "2014", id: "rn_YodiJO6k", title: "Otherside", artist: "Red Hot Chili Peppers", genre: "90s-rock" },
  { code: "2015", id: "h-Rnr3wTX9I", title: "This Is a Call", artist: "Foo Fighters", genre: "90s-rock" },
  { code: "2016", id: "O3dWBLoU--E", title: "Celebrity Skin", artist: "Hole", genre: "90s-rock" },
  { code: "2017", id: "3qVPNONdF58", title: "No Rain", artist: "Blind Melon", genre: "90s-rock" },
  { code: "2018", id: "ARiiO_41Id8", title: "Hanginaround", artist: "Counting Crows", genre: "90s-rock" },
  { code: "2019", id: "C-Naa1HXeDQ", title: "3AM", artist: "Matchbox Twenty", genre: "90s-rock" },
  { code: "2020", id: "f46ulX6uwGc", title: "All for You", artist: "Sister Hazel", genre: "90s-rock" },
  { code: "2021", id: "oFLysouG86I", title: "Time", artist: "Hootie & The Blowfish", genre: "90s-rock" },
  { code: "2022", id: "V5UOC0C0x8Q", title: "Plush", artist: "Stone Temple Pilots", genre: "90s-rock" },
  { code: "2023", id: "rE1oIhSgTgI", title: "How's It Going to Be", artist: "Third Eye Blind", genre: "90s-rock" },
  { code: "2024", id: "GpBFOJ3R0M4", title: "Only Happy When It Rains", artist: "Garbage", genre: "90s-rock" },
  { code: "2025", id: "h8MAHQhKe7Q", title: "Take a Picture", artist: "Filter", genre: "90s-rock" },
  { code: "2026", id: "qM0zINtulhM", title: "Alive", artist: "Pearl Jam", genre: "90s-rock" },
  { code: "2027", id: "kkcbxjWG9Mc", title: "Father of Mine", artist: "Everclear", genre: "90s-rock" },
  { code: "2028", id: "wsdy_rct6uo", title: "Two Princes", artist: "Spin Doctors", genre: "90s-rock" },
  { code: "2029", id: "Lgoz3XkW1UM", title: "Long Day", artist: "Matchbox Twenty", genre: "90s-rock" },
  { code: "2030", id: "CnQ8N1KacJc", title: "Good Riddance (Time of Your Life)", artist: "Green Day", genre: "90s-rock" },
  { code: "2031", id: "ah5gAkna3jI", title: "Hey Jealousy", artist: "Gin Blossoms", genre: "90s-rock" },
  { code: "2032", id: "EqWRaAF6_WY", title: "My Hero", artist: "Foo Fighters", genre: "90s-rock" },
  { code: "2033", id: "-nqRkAsZumc", title: "Stellar", artist: "Incubus", genre: "90s-rock" },
  { code: "2034", id: "YlUKcNNmywk", title: "Californication", artist: "Red Hot Chili Peppers", genre: "90s-rock" },
  { code: "2035", id: "n6P0SitRwy8", title: "Heart-Shaped Box", artist: "Nirvana", genre: "90s-rock" },
  { code: "2036", id: "5WPbqYoz9HA", title: "Machinehead", artist: "Bush", genre: "90s-rock" },
  { code: "2037", id: "NItKsTJiJ1Y", title: "Today", artist: "The Smashing Pumpkins", genre: "90s-rock" },
  { code: "2038", id: "E2Oe5YKhzCE", title: "Bound for the Floor", artist: "Local H", genre: "90s-rock" },
  { code: "2039", id: "9Ht5RZpzPqw", title: "All the Small Things", artist: "blink-182", genre: "90s-rock" },
  { code: "2040", id: "wYsMjEeEg4g", title: "Flagpole Sitta", artist: "Harvey Danger", genre: "90s-rock" },
  { code: "2041", id: "qfNmyxV2Ncw", title: "Cryin'", artist: "Aerosmith", genre: "90s-rock" },
  { code: "2042", id: "s-0PDROQrIo", title: "I Will Buy You a New Life", artist: "Everclear", genre: "90s-rock" },
  { code: "2043", id: "_m0bI82Rz_k", title: "Shine", artist: "Collective Soul", genre: "90s-rock" },
  { code: "2044", id: "5rOiW_xY-kc", title: "Everybody Hurts", artist: "R.E.M.", genre: "90s-rock" },
  { code: "2045", id: "o7sx32alzeE", title: "Til I Hear It from You", artist: "Gin Blossoms", genre: "90s-rock" },
  { code: "2046", id: "FNrQOUtXYOo", title: "I Alone", artist: "Live", genre: "90s-rock" },
  { code: "2047", id: "gRYZijLZR-Q", title: "Jumper", artist: "Third Eye Blind", genre: "90s-rock" },
  { code: "2048", id: "F_HoMkkRHv8", title: "The Distance", artist: "Cake", genre: "90s-rock" },
  { code: "2049", id: "ousaiByU1ko", title: "Run-Around", artist: "Blues Traveler", genre: "90s-rock" },
  { code: "2050", id: "1D5PtyrewSs", title: "A Long December", artist: "Counting Crows", genre: "90s-rock" },
  { code: "2051", id: "ENXvZ9YRjbo", title: "Say It Ain't So", artist: "Weezer", genre: "90s-rock" },
  { code: "2052", id: "MW6E_TNgCsY", title: "Santa Monica", artist: "Everclear", genre: "90s-rock" },
  { code: "2053", id: "2MRdtXWcgIw", title: "Adam's Song", artist: "blink-182", genre: "90s-rock" },
  { code: "2054", id: "bs0MO_d4Ukw", title: "Disarm", artist: "The Smashing Pumpkins", genre: "90s-rock" },
  { code: "2055", id: "Zs3xXlXSOKk", title: "It's All Been Done", artist: "Barenaked Ladies", genre: "90s-rock" },
  { code: "2056", id: "Zzyfcys1aLM", title: "One Headlight", artist: "The Wallflowers", genre: "90s-rock" },
  { code: "2057", id: "5LuH0ywYVQc", title: "Follow You Down", artist: "Gin Blossoms", genre: "90s-rock" },
  { code: "2058", id: "gYdlqjiQPAc", title: "Low", artist: "Cracker", genre: "90s-rock" },
  { code: "2059", id: "0Uc3ZrmhDN4", title: "What I Got", artist: "Sublime", genre: "90s-rock" },
  { code: "2060", id: "gl-JGJp-_CM", title: "Never Let You Go", artist: "Third Eye Blind", genre: "90s-rock" },
  { code: "2061", id: "yP4qdefD2To", title: "Slide", artist: "Goo Goo Dolls", genre: "90s-rock" },
  { code: "2062", id: "ilKcXIFi-Rc", title: "Connection", artist: "Elastica", genre: "90s-rock" },
  { code: "2063", id: "sT0g16_LQaQ", title: "Dammit", artist: "blink-182", genre: "90s-rock" },
  { code: "2064", id: "Abrn8aVQ76Q", title: "Self Esteem", artist: "The Offspring", genre: "90s-rock" },
  { code: "2065", id: "cXWbMu4PtpE", title: "Little Miss Can't Be Wrong", artist: "Spin Doctors", genre: "90s-rock" },
  { code: "2066", id: "-KT-r2vHeMM", title: "Sex & Candy", artist: "Marcy Playground", genre: "90s-rock" },
  { code: "2067", id: "PbgKEjNBHqM", title: "In Bloom", artist: "Nirvana", genre: "90s-rock" },
  { code: "2068", id: "Clxtg2pFTQM", title: "Counting Blue Cars", artist: "Dishwalla", genre: "90s-rock" },
  { code: "2069", id: "YgSPaXgAdzE", title: "Loser", artist: "Beck", genre: "90s-rock" },
  { code: "2070", id: "acK0KH2uJGc", title: "Good", artist: "Better Than Ezra", genre: "90s-rock" },
  { code: "2071", id: "PHzOOQfhPFg", title: "Just a Girl", artist: "No Doubt", genre: "90s-rock" },
  { code: "2072", id: "yQOBUrRaPU0", title: "Name", artist: "Goo Goo Dolls", genre: "90s-rock" },
  { code: "2073", id: "6exsatE-DUk", title: "December", artist: "Collective Soul", genre: "90s-rock" },
  { code: "2074", id: "sc5iTNVEOAg", title: "My Own Worst Enemy", artist: "Lit", genre: "90s-rock" },
  { code: "2075", id: "3GxUQ322jbY", title: "Let Me Go", artist: "Cake", genre: "90s-rock" },
  { code: "2076", id: "ht672-wYelc", title: "Vasoline", artist: "Stone Temple Pilots", genre: "90s-rock" },
  { code: "2077", id: "1VQ_3sBZEm0", title: "Learn to Fly", artist: "Foo Fighters", genre: "90s-rock" },
  { code: "2078", id: "NRtvqT_wMeY", title: "Runaway Train", artist: "Soul Asylum", genre: "90s-rock" },
  { code: "2079", id: "9TlBTPITo1I", title: "You Don't Know How It Feels", artist: "Tom Petty", genre: "90s-rock" },
  { code: "2080", id: "6uEJXodcME0", title: "Out of My Head", artist: "Fastball", genre: "90s-rock" },
  { code: "2081", id: "rPKYG_8L-bQ", title: "Best I Ever Had (Grey Sky Morning)", artist: "Vertical Horizon", genre: "90s-rock" },
  { code: "2082", id: "DL7-CKirWZE", title: "You Get What You Give", artist: "New Radicals", genre: "90s-rock" },
  { code: "2083", id: "7nqcL0mjMjw", title: "Livin' on the Edge", artist: "Aerosmith", genre: "90s-rock" },
  { code: "2084", id: "AVYYpNaSs2Y", title: "All I Want", artist: "Toad the Wet Sprocket", genre: "90s-rock" },
  { code: "2085", id: "FFOzayDpWoI", title: "Criminal", artist: "Fiona Apple", genre: "90s-rock" },
  { code: "2086", id: "pdz5kCaCRFM", title: "Hook", artist: "Blues Traveler", genre: "90s-rock" },
  { code: "2087", id: "NOG3eus4ZSo", title: "Tonight, Tonight", artist: "The Smashing Pumpkins", genre: "90s-rock" },
  { code: "2088", id: "EkwD5rQ-_d4", title: "Possum Kingdom", artist: "Toadies", genre: "90s-rock" },
  { code: "2089", id: "4HwW-BjipwY", title: "Free", artist: "The Martinis", genre: "90s-rock" },
  { code: "2090", id: "fgT9zGkiLig", title: "Drive", artist: "Incubus", genre: "90s-rock" },
  { code: "2091", id: "6ZktNItwexo", title: "Spiderwebs", artist: "No Doubt", genre: "90s-rock" },
  { code: "2092", id: "1jOk8dk-qaU", title: "Come Out and Play", artist: "The Offspring", genre: "90s-rock" },
  { code: "2093", id: "GqyposaQWnI", title: "Big Empty", artist: "Stone Temple Pilots", genre: "90s-rock" },
  { code: "2094", id: "aWmkuH1k7uA", title: "All Apologies (MTV Unplugged)", artist: "Nirvana", genre: "90s-rock" },
  { code: "2095", id: "sT1DdO3SISg", title: "Creep", artist: "Stone Temple Pilots", genre: "90s-rock" },
  { code: "2096", id: "xS3GiUAvjJ8", title: "Comedown", artist: "Bush", genre: "90s-rock" },
  { code: "2097", id: "hee0aUVnK1U", title: "All Over You", artist: "Live", genre: "90s-rock" },
  { code: "2098", id: "qDoiZc25t-k", title: "I Walk Alone", artist: "Oleander", genre: "90s-rock" },
  { code: "2099", id: "_4BObpNQqNo", title: "Better Man (Live)", artist: "Pearl Jam", genre: "90s-rock" },
  { code: "2100", id: "PCsGRCf8T9Y", title: "In the Meantime", artist: "Spacehog", genre: "90s-rock" },
  { code: "2101", id: "_uDiGAr_WKs", title: "When I Grow Up", artist: "Garbage", genre: "90s-rock" },
  { code: "2102", id: "DKxXHEx-XnU", title: "Better Days (And the Bottom Drops Out)", artist: "Citizen King", genre: "90s-rock" },
  { code: "2103", id: "NjNn4bbbgSw", title: "Cumbersome", artist: "Seven Mary Three", genre: "90s-rock" },
  { code: "2104", id: "7qFfFVSerQo", title: "High and Dry", artist: "Radiohead", genre: "90s-rock" },
  { code: "2105", id: "8LhCd1W2V0Q", title: "Are You Gonna Go My Way", artist: "Lenny Kravitz", genre: "90s-rock" },
  { code: "2106", id: "cH_rfGBwamc", title: "Violet", artist: "Hole", genre: "90s-rock" },
  { code: "2107", id: "i7Q_8q3XXrQ", title: "Jane Says", artist: "Jane's Addiction", genre: "90s-rock" },
  { code: "2108", id: "YxS4lqppZ6Y", title: "Sour Girl", artist: "Stone Temple Pilots", genre: "90s-rock" },
  { code: "2109", id: "n7TLTjqUyog", title: "The World I Know", artist: "Collective Soul", genre: "90s-rock" },
  { code: "2110", id: "1umEXpGHc0E", title: "The Freshmen", artist: "The Verve Pipe", genre: "90s-rock" },
  { code: "2111", id: "x1vOVki-a1s", title: "Rock 'n' Roll Lifestyle", artist: "Cake", genre: "90s-rock" },
  { code: "2112", id: "fxvkI9MTQw4", title: "Cannonball", artist: "The Breeders", genre: "90s-rock" },
  { code: "2113", id: "NIGMUAMevH0", title: "The Impression That I Get", artist: "The Mighty Mighty Bosstones", genre: "90s-rock" },
  { code: "2114", id: "GeFr4_CADp4", title: "Ruby Soho", artist: "Rancid", genre: "90s-rock" },
  { code: "2115", id: "VQJp135efOY", title: "Selling the Drama", artist: "Live", genre: "90s-rock" },
  { code: "2116", id: "0XcN12uVHeQ", title: "Soul to Squeeze", artist: "Red Hot Chili Peppers", genre: "90s-rock" },
  { code: "2117", id: "Ln6WQqRDrCo", title: "Only Wanna Be with You", artist: "Hootie & The Blowfish", genre: "90s-rock" },
  { code: "2118", id: "NPcyTyilmYY", title: "You Oughta Know", artist: "Alanis Morissette", genre: "90s-rock" },
  { code: "2119", id: "V0rV88Ev-og", title: "In the Garage", artist: "Weezer", genre: "90s-rock" },
  { code: "2120", id: "42BBdzzgPNM", title: "Longview", artist: "Green Day", genre: "90s-rock" },
  { code: "2121", id: "X5jlTlUTWfQ", title: "The Way", artist: "Fastball", genre: "90s-rock" },
  { code: "2122", id: "1qB6XdAkkAo", title: "Found Out About You", artist: "Gin Blossoms", genre: "90s-rock" },
  { code: "2123", id: "raRGnueg8Lo", title: "Special", artist: "Garbage", genre: "90s-rock" },
  { code: "2124", id: "-lDIJjnCHco", title: "Open Up Your Eyes", artist: "Tonic", genre: "90s-rock" },
  { code: "2125", id: "kbwzPzJ6wCU", title: "Broadway", artist: "Goo Goo Dolls", genre: "90s-rock" },
  { code: "2126", id: "PjsMnvqL7eY", title: "Tomorrow", artist: "Silverchair", genre: "90s-rock" },
  { code: "2127", id: "OMaycNcPsHI", title: "Every You Every Me", artist: "Placebo", genre: "90s-rock" },
  { code: "2128", id: "JJFGhFtKxPc", title: "Spit on a Stranger", artist: "Pavement", genre: "90s-rock" },
  { code: "2129", id: "tI-5uv4wryI", title: "Champagne Supernova", artist: "Oasis", genre: "90s-rock" },
  { code: "2130", id: "xGytDsqkQY8", title: "Closing Time", artist: "Semisonic", genre: "90s-rock" },
  { code: "2200", id: "TIy3n2b7V9k", title: "Sk8er Boi", artist: "Avril Lavigne", genre: "2000s" },
  { code: "2201", id: "5NPBIwQyPWE", title: "Complicated", artist: "Avril Lavigne", genre: "2000s" },
  { code: "2202", id: "0Gl2QnHNpkA", title: "As Long as You Love Me", artist: "Backstreet Boys", genre: "2000s" },
  { code: "2203", id: "6M6samPEMpM", title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", genre: "2000s" },
  { code: "2204", id: "Eo-KmOd3i7s", title: "Bye Bye Bye", artist: "*NSYNC", genre: "2000s" },
  { code: "2205", id: "MEb2CecR11I", title: "Larger than Life", artist: "Backstreet Boys", genre: "2000s" },
  { code: "2206", id: "vx2u5uUu3DE", title: "It's My Life", artist: "Bon Jovi", genre: "2000s" },
  { code: "2207", id: "eVTXPUF4Oz4", title: "In the End", artist: "Linkin Park", genre: "2000s" },
  { code: "2208", id: "3YxaaGgTQYM", title: "Bring Me to Life ft. Paul McCoy", artist: "Evanescence", genre: "2000s" },
  { code: "2209", id: "CDl9ZMfj6aE", title: "Smooth Criminal", artist: "Alien Ant Farm", genre: "2000s" },
  { code: "2210", id: "RYnFIRc0k6E", title: "Rollin' (Air Raid Vehicle)", artist: "Limp Bizkit", genre: "2000s" },
  { code: "2211", id: "j0lSpNtjPM8", title: "Last Resort", artist: "Papa Roach", genre: "2000s" },
  { code: "2212", id: "CSvFpBOe8eY", title: "Chop Suey!", artist: "System of a Down", genre: "2000s" },
  { code: "2213", id: "CMX2lPum_pg", title: "Fat Lip", artist: "Sum 41", genre: "2000s" },
  { code: "2214", id: "JTMVOzPPtiw", title: "Nookie", artist: "Limp Bizkit", genre: "2000s" },
  { code: "2215", id: "BE9CXWV1alg", title: "My Generation", artist: "Limp Bizkit", genre: "2000s" },
  { code: "2216", id: "qex0OjXolzc", title: "Boiler", artist: "Limp Bizkit", genre: "2000s" },
  { code: "2217", id: "jRGrNDV2mKc", title: "Freak on a Leash", artist: "Korn", genre: "2000s" },
  { code: "2218", id: "9QWOc0HnItM", title: "Re-Arranged", artist: "Limp Bizkit", genre: "2000s" },
  { code: "2219", id: "Ypkv0HeUvTc", title: "The Beautiful People", artist: "Marilyn Manson", genre: "2000s" },
  { code: "2220", id: "7QU1nvuxaMA", title: "Like a Stone", artist: "Audioslave", genre: "2000s" },
  { code: "2221", id: "eW2qlKa6oHw", title: "Again", artist: "Lenny Kravitz", genre: "2000s" },
  { code: "2222", id: "fV4DiAyExN0", title: "The Reason", artist: "Hoobastank", genre: "2000s" },
  { code: "2223", id: "CduA0TULnow", title: "Oops!... I Did It Again", artist: "Britney Spears", genre: "2000s" },
  { code: "2224", id: "t0bPrt69rag", title: "Sometimes", artist: "Britney Spears", genre: "2000s" },
  { code: "2225", id: "PZYSiWHW8V0", title: "Overprotected", artist: "Britney Spears", genre: "2000s" },
  { code: "2226", id: "AJWtLf4-WWs", title: "Stronger", artist: "Britney Spears", genre: "2000s" },
  { code: "2227", id: "Q4VK9_CfOLQ", title: "(You Drive Me) Crazy", artist: "Britney Spears", genre: "2000s" },
  { code: "2228", id: "RQa7SvVCdZk", title: "Lady Marmalade", artist: "Christina Aguilera, Lil' Kim, Mya & P!nk", genre: "2000s" },
  { code: "2229", id: "eAfyFTzZDMM", title: "Beautiful", artist: "Christina Aguilera", genre: "2000s" },
  { code: "2230", id: "gZHjRQjbHrE", title: "Hollaback Girl", artist: "Gwen Stefani", genre: "2000s" },
  { code: "2231", id: "YNSxNsr4wmA", title: "Don't Cha ft. Busta Rhymes", artist: "The Pussycat Dolls", genre: "2000s" },
  { code: "2232", id: "VCLxJd1d84s", title: "Buttons ft. Snoop Dogg", artist: "The Pussycat Dolls", genre: "2000s" },
  { code: "2233", id: "-hMC8pQkEmk", title: "Pero Me Acuerdo de Ti", artist: "Christina Aguilera", genre: "2000s" },
  { code: "2234", id: "1r9ghI7YcL0", title: "Beep ft. will.i.am", artist: "The Pussycat Dolls", genre: "2000s" },
  { code: "2235", id: "QrOe2h9RtWI", title: "Beautiful Liar", artist: "Beyoncé & Shakira", genre: "2000s" },
  { code: "2236", id: "0J3vgcE5i2o", title: "Promiscuous ft. Timbaland", artist: "Nelly Furtado", genre: "2000s" },
  { code: "2237", id: "5T0utQ-XWGY", title: "Fergalicious", artist: "Fergie", genre: "2000s" },
  { code: "2238", id: "6JnGBs88sL0", title: "Say It Right", artist: "Nelly Furtado", genre: "2000s" },
  { code: "2239", id: "PLolag3YSYU", title: "Maneater", artist: "Nelly Furtado", genre: "2000s" },
  { code: "2240", id: "kOL7aeIDruA", title: "Turn Off the Light", artist: "Nelly Furtado", genre: "2000s" },
  { code: "2241", id: "roPQ_M3yJTA", title: "I'm Like a Bird", artist: "Nelly Furtado", genre: "2000s" },
  { code: "2242", id: "CvBfHwUxHIk", title: "Umbrella ft. JAŸ-Z", artist: "Rihanna", genre: "2000s" },
  { code: "2243", id: "WEQ0l_m3Xm0", title: "I Try", artist: "Macy Gray", genre: "2000s" },
  { code: "2244", id: "8WYHDfJDPDc", title: "Dilemma ft. Kelly Rowland", artist: "Nelly", genre: "2000s" },
  { code: "2245", id: "HKLnmMacEB4", title: "The Game of Love ft. Michelle Branch", artist: "Santana", genre: "2000s" },
  { code: "2246", id: "RtSDWq6HsJE", title: "Ride wit Me ft. St. Lunatics", artist: "Nelly", genre: "2000s" },
  { code: "2247", id: "gOMhN-hfMtY", title: "Stan ft. Dido", artist: "Eminem", genre: "2000s" },
  { code: "2248", id: "eJO5HU_7_1w", title: "The Real Slim Shady", artist: "Eminem", genre: "2000s" },
  { code: "2249", id: "D4hAVemuQXY", title: "Sing for the Moment", artist: "Eminem", genre: "2000s" },
  { code: "2250", id: "RQ9_TKayu9s", title: "Cleanin' Out My Closet", artist: "Eminem", genre: "2000s" },
  { code: "2251", id: "bD3S3kurYVA", title: "Lose Yourself", artist: "Eminem", genre: "2000s" },
  { code: "2252", id: "tr-H8dR0HLo", title: "Ain't It Funny ft. Ja Rule", artist: "Jennifer Lopez", genre: "2000s" },
  { code: "2253", id: "4kGvlESGvbs", title: "Love Don't Cost a Thing", artist: "Jennifer Lopez", genre: "2000s" },
  { code: "2254", id: "6oqXVx3sBOk", title: "Coffee & TV", artist: "Blur", genre: "2000s" },
  { code: "2255", id: "mMfxI3r_LyA", title: "Lady (Hear Me Tonight)", artist: "Modjo", genre: "2000s" },
  { code: "2256", id: "hTl0F2cKzLk", title: "Chillin'", artist: "Modjo", genre: "2000s" },
  { code: "2257", id: "4JkIs37a2JE", title: "Virtual Insanity", artist: "Jamiroquai", genre: "2000s" },
  { code: "2258", id: "EDwb9jOVRtU", title: "Hung Up", artist: "Madonna", genre: "2000s" },
  { code: "2259", id: "w4AQbsCz1AY", title: "King for a Day", artist: "Jamiroquai", genre: "2000s" },
  { code: "2260", id: "c18441Eh_WE", title: "Can't Get You Out of My Head", artist: "Kylie Minogue", genre: "2000s" },
  { code: "2261", id: "63vqob-MljQ", title: "Come into My World", artist: "Kylie Minogue", genre: "2000s" },
  { code: "2262", id: "4hGQ97tCTOs", title: "GoldenEye", artist: "Tina Turner", genre: "2000s" },
  { code: "2263", id: "PSu5nAQ7uZw", title: "Here with Me", artist: "Dido", genre: "2000s" },
  { code: "2264", id: "RB-RcX5DS5A", title: "The Scientist", artist: "Coldplay", genre: "2000s" },
  { code: "2265", id: "IJWlBfo5Oj0", title: "Porcelain", artist: "Moby", genre: "2000s" },
  { code: "2266", id: "SC6-TiN19uE", title: "Natural Blues ft. Christina Ricci", artist: "Moby", genre: "2000s" },
  { code: "2267", id: "jhC1pI76Rqo", title: "Everybody's Fool", artist: "Evanescence", genre: "2000s" },
  { code: "2268", id: "LQj--Kjn0z8", title: "Walkin' on the Sun", artist: "Smash Mouth", genre: "2000s" },
  { code: "2269", id: "2s3iGpDqQpQ", title: "Falling Away from Me", artist: "Korn", genre: "2000s" },
  { code: "2270", id: "Z0GFRcFm-aY", title: "It's the End of the World as We Know It (and I Feel Fine)", artist: "R.E.M.", genre: "2000s" },
  { code: "2271", id: "wCDIYvFmgW8", title: "Weapon of Choice ft. Bootsy Collins", artist: "Fatboy Slim", genre: "2000s" },
  { code: "2272", id: "ub747pprmJ8", title: "Right Here, Right Now", artist: "Fatboy Slim", genre: "2000s" },
  { code: "2273", id: "Co0tTeuUVhU", title: "Heartless", artist: "Kanye West", genre: "2000s" },
  { code: "2274", id: "bd2B6SjMh_w", title: "Crazy", artist: "Gnarls Barkley", genre: "2000s" },
  { code: "2275", id: "araU0fZj6oQ", title: "It's Been Awhile", artist: "Staind", genre: "2000s" },
  { code: "2276", id: "O-fyNgHdmLI", title: "My Sacrifice", artist: "Creed", genre: "2000s" },
  { code: "2277", id: "iCz8R25hlFI", title: "J'en ai marre! (Live)", artist: "Alizée", genre: "2000s" },
  { code: "2278", id: "KyM7sw4lVSk", title: "La Isla Bonita", artist: "Alizée", genre: "2000s" },
  { code: "2279", id: "zfXBNQMj2SE", title: "Moi... Lolita (Live)", artist: "Alizée", genre: "2000s" },
  { code: "2280", id: "JJ6clbNFCJM", title: "Amélie m'a dit", artist: "Alizée", genre: "2000s" },
  { code: "2281", id: "_ao2u7F_Qzg", title: "In the Shadows", artist: "The Rasmus", genre: "2000s" },
  { code: "2400", id: "RgKAFK5djSk", title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", genre: "hip-hop" },
  { code: "2401", id: "YVkUvmDQ3HY", title: "Without Me", artist: "Eminem", genre: "hip-hop" },
  { code: "2402", id: "uelHwf8o7_U", title: "Love The Way You Lie", artist: "Eminem ft. Rihanna", genre: "hip-hop" },
  { code: "2403", id: "QK8mJJJvaes", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis", genre: "hip-hop" },
  { code: "2404", id: "VrDfSZ_6f4U", title: "Day 'N' Nite", artist: "Kid Cudi", genre: "hip-hop" },
  { code: "2405", id: "UePtoxDhJSw", title: "Black And Yellow", artist: "Wiz Khalifa", genre: "hip-hop" },
  { code: "2406", id: "vk6014HuxcE", title: "Empire State Of Mind ft. Alicia Keys", artist: "JAŸ-Z", genre: "hip-hop" },
  { code: "2407", id: "fPO76Jlnz6c", title: "Gangsta's Paradise (feat. L.V.)", artist: "Coolio", genre: "hip-hop" },
  { code: "2408", id: "h4UqMyldS7Q", title: "It Was A Good Day", artist: "Ice Cube", genre: "hip-hop" },
  { code: "2409", id: "8GliyDgAGQI", title: "Nuthin' But A \"G\" Thang", artist: "Dr. Dre", genre: "hip-hop" },
  { code: "2410", id: "mYn6Vz9X0VQ", title: "Boys In the Hood", artist: "N.W.A.", genre: "hip-hop" },
  { code: "2411", id: "qZuxPKUVGiw", title: "Fuk Da Police", artist: "N.W.A.", genre: "hip-hop" },
  { code: "2412", id: "uo35R9zQsAI", title: "My House", artist: "Flo Rida", genre: "hip-hop" },
  { code: "2413", id: "O-zpOMYRi0w", title: "Fancy ft. Charli XCX", artist: "Iggy Azalea", genre: "hip-hop" },
  { code: "2500", id: "kJQP7kiw5Fk", title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", genre: "latin" },
  { code: "2501", id: "pRpeEdMmmQ0", title: "Waka Waka", artist: "Shakira", genre: "latin" },
  { code: "2600", id: "OPf0YbXqDm0", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", genre: "funk" },
  { code: "2601", id: "Gs069dndIYk", title: "September", artist: "Earth, Wind & Fire", genre: "funk" },
  { code: "2602", id: "y6Sxv-sUYtM", title: "Happy", artist: "Pharrell Williams", genre: "funk" },
  { code: "2700", id: "8UVNT4wvIGY", title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", genre: "indie" },
  { code: "2701", id: "gGdGFtwCNBE", title: "Mr. Brightside", artist: "The Killers", genre: "indie" },
  { code: "2702", id: "RBumgq5yVrA", title: "Let Her Go", artist: "Passenger", genre: "indie" },
  { code: "2703", id: "Sv6dMFF_yts", title: "We Are Young ft. Janelle Monáe", artist: "fun.", genre: "indie" },
  { code: "2704", id: "Y66j_BUCBMY", title: "Best Day Of My Life", artist: "American Authors", genre: "indie" },
  { code: "2705", id: "mE6DLY7WQkg", title: "Waste", artist: "Foster The People", genre: "indie" },
  { code: "2706", id: "nlcIKh6sBtc", title: "Royals", artist: "Lorde", genre: "indie" },
  { code: "2707", id: "rprf7LEraU4", title: "Sleepwalking", artist: "The Chain Gang Of 1974", genre: "indie" },
  { code: "2708", id: "N3zf9q8mbWs", title: "The Setup", artist: "Favored Nations", genre: "indie" },
  { code: "2709", id: "d4KOfBx_XPM", title: "Don't Come Close", artist: "Yeasayer", genre: "indie" },
  { code: "2800", id: "60ItHLz5WEA", title: "Faded", artist: "Alan Walker", genre: "electronic" },
  { code: "2801", id: "papuvlVeZg8", title: "Rockabye", artist: "Clean Bandit ft. Sean Paul & Anne-Marie", genre: "electronic" },
  { code: "2802", id: "SkTt9k4Y-a8", title: "Sorry For Party Rocking", artist: "LMFAO", genre: "electronic" },
  { code: "2803", id: "KQ6zr6kCPj8", title: "Party Rock Anthem ft. Lauren Bennett, GoonRock", artist: "LMFAO", genre: "electronic" },
  { code: "2804", id: "wyx6JDQCslE", title: "Sexy and I Know It", artist: "LMFAO", genre: "electronic" },
  { code: "2805", id: "CdLhdrNgGu4", title: "Let's Get Ridiculous", artist: "Redfoo", genre: "electronic" },
  { code: "2900", id: "ALV-QtDFpSw", title: "Play It Again", artist: "Luke Bryan", genre: "country" },
  { code: "2901", id: "CbxuXq_981s", title: "This Is How We Roll ft. Luke Bryan", artist: "Florida Georgia Line", genre: "country" },
  { code: "2902", id: "IZbN_nmxAGk", title: "Whiskey Lullaby ft. Alison Krauss", artist: "Brad Paisley", genre: "country" },
  { code: "2903", id: "6l3ukWqRU4s", title: "Huntin', Fishin', And Lovin' Every Day", artist: "Luke Bryan", genre: "country" },
  { code: "2904", id: "e4ujS1er1r0", title: "Chicken Fried", artist: "Zac Brown Band", genre: "country" },
  { code: "2905", id: "hvKyBcCDOB4", title: "Wagon Wheel", artist: "Darius Rucker", genre: "country" },
  { code: "2906", id: "QrM39m22jH4", title: "Drunk On A Plane", artist: "Dierks Bentley", genre: "country" },
  { code: "2907", id: "Lb9q1ScC4cg", title: "Dirt Road Anthem", artist: "Jason Aldean", genre: "country" },
  { code: "2908", id: "p1oL37ycONQ", title: "Round Here", artist: "Florida Georgia Line", genre: "country" },
  { code: "2909", id: "PT4ryVop_Fc", title: "May We All ft. Tim McGraw", artist: "Florida Georgia Line", genre: "country" },
  { code: "2910", id: "i_XGnxTi-fE", title: "The Devil Went Down to Georgia", artist: "The Charlie Daniels Band", genre: "country" },
  { code: "2911", id: "xdImDqbgc2g", title: "Burnin' It Down", artist: "Jason Aldean", genre: "country" },
  { code: "2912", id: "HpFaI0dKAHc", title: "Drunk On You", artist: "Luke Bryan", genre: "country" },
  { code: "2913", id: "5tXh_MfrMe0", title: "Life Is a Highway", artist: "Rascal Flatts", genre: "country" },
  { code: "2914", id: "42uphHWxmFU", title: "Dirt", artist: "Florida Georgia Line", genre: "country" },
  { code: "2915", id: "8PvebsWcpto", title: "Cruise", artist: "Florida Georgia Line", genre: "country" },
  { code: "2916", id: "oajuSNChUOo", title: "Get Your Shine On", artist: "Florida Georgia Line", genre: "country" },
  { code: "2917", id: "ldQrapQ4d0Y", title: "As Good As I Once Was", artist: "Toby Keith", genre: "country" },
  { code: "2918", id: "T_igmjEB560", title: "Stay", artist: "Florida Georgia Line", genre: "country" },
  { code: "2919", id: "7qH4qyi1-Ys", title: "What Hurts The Most", artist: "Rascal Flatts", genre: "country" },
  { code: "2920", id: "zXDAYlhdkyg", title: "H.O.L.Y.", artist: "Florida Georgia Line", genre: "country" },
  { code: "2921", id: "8AHCfZTRGiI", title: "Hurt", artist: "Johnny Cash", genre: "country" },
  { code: "2922", id: "-Fulz4ytZ54", title: "I Love This Bar", artist: "Toby Keith", genre: "country" },
  { code: "2923", id: "XHaVmFKnK7w", title: "Cry, Cry, Cry", artist: "Johnny Cash", genre: "country" },
  { code: "2924", id: "IH1Z9DEDqpk", title: "Why Don't We Just Dance", artist: "Josh Turner", genre: "country" },
  { code: "2925", id: "-q0LE3gtUn8", title: "Lover, Lover", artist: "Jerrod Niemann", genre: "country" },
  { code: "2926", id: "97BfC4LgrXk", title: "What Do You Want", artist: "Jerrod Niemann", genre: "country" },
  { code: "2927", id: "MaAF_3WMJGM", title: "Made In America", artist: "Toby Keith", genre: "country" },
  { code: "2928", id: "KmxaY_OVvWA", title: "Highway Don't Care ft. Taylor Swift, Keith Urban", artist: "Tim McGraw", genre: "country" },
  { code: "2929", id: "_l0pqnBoozs", title: "Hell Raisin' Heat of the Summer", artist: "Florida Georgia Line", genre: "country" },
  { code: "2930", id: "awzNHuGqoMc", title: "Humble And Kind", artist: "Tim McGraw", genre: "country" },
  { code: "2931", id: "-vn6QdqxK3g", title: "Don't Take The Girl", artist: "Tim McGraw", genre: "country" },
];
