// The video menu. Every video has a 3-digit request code; the first digit
// groups it by genre (1xx pop, 2xx rock, 3xx 80s, 4xx hip-hop, 5xx latin,
// 6xx funk, 7xx indie, 8xx electronic, 901-949 country). 950-999 is reserved for
// videos viewers add themselves. Add entries freely:
// { code: "123", id: "<YouTube video id>", title: "Song", artist: "Artist", genre: "pop" }
// Videos that refuse to embed are skipped automatically at runtime.
window.VIDEO_POOL = [
  { code: "101", id: "dQw4w9WgXcQ", title: "Never Gonna Give You Up", artist: "Rick Astley", genre: "pop" },
  { code: "501", id: "kJQP7kiw5Fk", title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", genre: "latin" },
  { code: "102", id: "JGwWNGJdvx8", title: "Shape of You", artist: "Ed Sheeran", genre: "pop" },
  { code: "601", id: "OPf0YbXqDm0", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", genre: "funk" },
  { code: "103", id: "9bZkp7q19f0", title: "Gangnam Style", artist: "PSY", genre: "pop" },
  { code: "201", id: "fJ9rUzIMcZQ", title: "Bohemian Rhapsody", artist: "Queen", genre: "rock" },
  { code: "202", id: "hTWKbfoikeg", title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "rock" },
  { code: "104", id: "YQHsXMglC9A", title: "Hello", artist: "Adele", genre: "pop" },
  { code: "105", id: "hLQl3WQQoQ0", title: "Someone Like You", artist: "Adele", genre: "pop" },
  { code: "106", id: "rYEDA3JcQqw", title: "Rolling in the Deep", artist: "Adele", genre: "pop" },
  { code: "107", id: "CevxZvSJLk8", title: "Roar", artist: "Katy Perry", genre: "pop" },
  { code: "108", id: "0KSOMA3QBU0", title: "Dark Horse", artist: "Katy Perry", genre: "pop" },
  { code: "401", id: "RgKAFK5djSk", title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth", genre: "hip-hop" },
  { code: "801", id: "60ItHLz5WEA", title: "Faded", artist: "Alan Walker", genre: "electronic" },
  { code: "502", id: "pRpeEdMmmQ0", title: "Waka Waka", artist: "Shakira", genre: "latin" },
  { code: "109", id: "2Vv-BfVoq4g", title: "Perfect", artist: "Ed Sheeran", genre: "pop" },
  { code: "110", id: "lp-EO5I60KA", title: "Thinking Out Loud", artist: "Ed Sheeran", genre: "pop" },
  { code: "111", id: "e-ORhEE9VVg", title: "Blank Space", artist: "Taylor Swift", genre: "pop" },
  { code: "112", id: "nfWlot6h_JM", title: "Shake It Off", artist: "Taylor Swift", genre: "pop" },
  { code: "113", id: "hT_nvWreIhg", title: "Counting Stars", artist: "OneRepublic", genre: "pop" },
  { code: "301", id: "djV11Xbc914", title: "Take On Me", artist: "a-ha", genre: "80s" },
  { code: "302", id: "btPJPFnesV4", title: "Eye of the Tiger", artist: "Survivor", genre: "80s" },
  { code: "303", id: "PIb6AZdTr-A", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", genre: "80s" },
  { code: "203", id: "lDK9QqIzhwk", title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "rock" },
  { code: "204", id: "1w7OgIMMRc4", title: "Sweet Child O' Mine", artist: "Guns N' Roses", genre: "rock" },
  { code: "205", id: "v2AC41dglnM", title: "Thunderstruck", artist: "AC/DC", genre: "rock" },
  { code: "304", id: "Zi_XLOBDo_Y", title: "Billie Jean", artist: "Michael Jackson", genre: "80s" },
  { code: "305", id: "sOnqjkJTMaA", title: "Thriller", artist: "Michael Jackson", genre: "80s" },
  { code: "114", id: "4NRXx6U8ABQ", title: "Blinding Lights", artist: "The Weeknd", genre: "pop" },
  { code: "402", id: "YVkUvmDQ3HY", title: "Without Me", artist: "Eminem", genre: "hip-hop" },
  { code: "403", id: "uelHwf8o7_U", title: "Love The Way You Lie", artist: "Eminem ft. Rihanna", genre: "hip-hop" },
  { code: "404", id: "QK8mJJJvaes", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis", genre: "hip-hop" },
  { code: "701", id: "8UVNT4wvIGY", title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", genre: "indie" },
  { code: "206", id: "bx1Bh8ZvH84", title: "Wonderwall", artist: "Oasis", genre: "rock" },
  { code: "207", id: "1lyu1KKwC74", title: "Bitter Sweet Symphony", artist: "The Verve", genre: "rock" },
  { code: "702", id: "gGdGFtwCNBE", title: "Mr. Brightside", artist: "The Killers", genre: "indie" },
  { code: "208", id: "0J2QdDbelmY", title: "Seven Nation Army", artist: "The White Stripes", genre: "rock" },
  { code: "209", id: "Soa3gO7tL-c", title: "Boulevard of Broken Dreams", artist: "Green Day", genre: "rock" },
  { code: "210", id: "L_jWHffIx5E", title: "All Star", artist: "Smash Mouth", genre: "rock" },
  { code: "602", id: "Gs069dndIYk", title: "September", artist: "Earth, Wind & Fire", genre: "funk" },
  { code: "115", id: "09R8_2nJtjg", title: "Sugar", artist: "Maroon 5", genre: "pop" },
  { code: "802", id: "papuvlVeZg8", title: "Rockabye", artist: "Clean Bandit ft. Sean Paul & Anne-Marie", genre: "electronic" },
  { code: "116", id: "k2qgadSvNyU", title: "New Rules", artist: "Dua Lipa", genre: "pop" },
  { code: "211", id: "ktvTqknDobU", title: "Radioactive", artist: "Imagine Dragons", genre: "rock" },
  { code: "212", id: "7wtfhZwyrcc", title: "Believer", artist: "Imagine Dragons", genre: "rock" },
  { code: "213", id: "fKopy74weus", title: "Thunder", artist: "Imagine Dragons", genre: "rock" },
  { code: "117", id: "YykjpeuMNEk", title: "Hymn for the Weekend", artist: "Coldplay", genre: "pop" },
  { code: "118", id: "dvgZkm1xWPE", title: "Viva La Vida", artist: "Coldplay", genre: "pop" },
  { code: "703", id: "RBumgq5yVrA", title: "Let Her Go", artist: "Passenger", genre: "indie" },
  { code: "603", id: "y6Sxv-sUYtM", title: "Happy", artist: "Pharrell Williams", genre: "funk" },
  { code: "119", id: "450p7goxZqg", title: "All of Me", artist: "John Legend", genre: "pop" },
  { code: "120", id: "2vjPBrBU-TM", title: "Chandelier", artist: "Sia", genre: "pop" },
  { code: "124", id: "KRaWnd3LJfs", title: "Payphone ft. Wiz Khalifa", artist: "Maroon 5", genre: "pop" },
  { code: "704", id: "Sv6dMFF_yts", title: "We Are Young ft. Janelle Monáe", artist: "fun.", genre: "indie" },
  { code: "125", id: "psuRGfAaju4", title: "Fireflies", artist: "Owl City", genre: "pop" },
  { code: "126", id: "fwK7ggA3-bU", title: "One More Night", artist: "Maroon 5", genre: "pop" },
  { code: "127", id: "fWNaR-rxAic", title: "Call Me Maybe", artist: "Carly Rae Jepsen", genre: "pop" },
  { code: "128", id: "kVpv8-5XWOI", title: "Hey, Soul Sister", artist: "Train", genre: "pop" },
  { code: "129", id: "M11SvDtPBhA", title: "Party In The U.S.A.", artist: "Miley Cyrus", genre: "pop" },
  { code: "130", id: "QGJuMBdaqIw", title: "Firework", artist: "Katy Perry", genre: "pop" },
  { code: "131", id: "qrO4YZeyl0I", title: "Bad Romance", artist: "Lady Gaga", genre: "pop" },
  { code: "132", id: "bESGLojNYSo", title: "Poker Face", artist: "Lady Gaga", genre: "pop" },
  { code: "133", id: "uSD4vsh1zDA", title: "I Gotta Feeling", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "134", id: "4m48GqaOz90", title: "Boom Boom Pow", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "803", id: "SkTt9k4Y-a8", title: "Sorry For Party Rocking", artist: "LMFAO", genre: "electronic" },
  { code: "804", id: "KQ6zr6kCPj8", title: "Party Rock Anthem ft. Lauren Bennett, GoonRock", artist: "LMFAO", genre: "electronic" },
  { code: "135", id: "fLexgOxsZu0", title: "The Lazy Song", artist: "Bruno Mars", genre: "pop" },
  { code: "136", id: "iEPTlhBmwRg", title: "Moves Like Jagger ft. Christina Aguilera", artist: "Maroon 5", genre: "pop" },
  { code: "137", id: "Vysgv7qVYTo", title: "Dynamite", artist: "Taio Cruz", genre: "pop" },
  { code: "405", id: "VrDfSZ_6f4U", title: "Day 'N' Nite", artist: "Kid Cudi", genre: "hip-hop" },
  { code: "406", id: "UePtoxDhJSw", title: "Black And Yellow", artist: "Wiz Khalifa", genre: "hip-hop" },
  { code: "407", id: "vk6014HuxcE", title: "Empire State Of Mind ft. Alicia Keys", artist: "JAŸ-Z", genre: "hip-hop" },
  { code: "408", id: "fPO76Jlnz6c", title: "Gangsta's Paradise (feat. L.V.)", artist: "Coolio", genre: "hip-hop" },
  { code: "214", id: "CxKWTzr-k6s", title: "Even Flow", artist: "Pearl Jam", genre: "rock" },
  { code: "805", id: "wyx6JDQCslE", title: "Sexy and I Know It", artist: "LMFAO", genre: "electronic" },
  { code: "138", id: "6g6g2mvItp4", title: "Misery", artist: "Maroon 5", genre: "pop" },
  { code: "139", id: "ZaI2IlHwmgQ", title: "Pump It", artist: "The Black Eyed Peas", genre: "pop" },
  { code: "140", id: "kTHNpusq654", title: "Hot N Cold", artist: "Katy Perry", genre: "pop" },
  { code: "141", id: "Y7ix6RITXM0", title: "Maps", artist: "Maroon 5", genre: "pop" },
  { code: "142", id: "F57P9C4SAW4", title: "California Gurls ft. Snoop Dogg", artist: "Katy Perry", genre: "pop" },
  { code: "143", id: "LjhCEhWiKXk", title: "Just The Way You Are", artist: "Bruno Mars", genre: "pop" },
  { code: "806", id: "CdLhdrNgGu4", title: "Let's Get Ridiculous", artist: "Redfoo", genre: "electronic" },
  { code: "144", id: "ZyhrYis509A", title: "Barbie Girl", artist: "Aqua", genre: "pop" },
  { code: "215", id: "0mYBSayCsH0", title: "I'm A Believer", artist: "Smash Mouth", genre: "rock" },
  { code: "409", id: "h4UqMyldS7Q", title: "It Was A Good Day", artist: "Ice Cube", genre: "hip-hop" },
  { code: "145", id: "NOubzHCUt48", title: "Die Young", artist: "Ke$ha", genre: "pop" },
  { code: "410", id: "8GliyDgAGQI", title: "Nuthin' But A \"G\" Thang", artist: "Dr. Dre", genre: "hip-hop" },
  { code: "146", id: "VuNIsY6JdUw", title: "You Belong With Me", artist: "Taylor Swift", genre: "pop" },
  { code: "411", id: "mYn6Vz9X0VQ", title: "Boys In the Hood", artist: "N.W.A.", genre: "hip-hop" },
  { code: "412", id: "qZuxPKUVGiw", title: "Fuk Da Police", artist: "N.W.A.", genre: "hip-hop" },
  { code: "413", id: "uo35R9zQsAI", title: "My House", artist: "Flo Rida", genre: "hip-hop" },
  { code: "901", id: "ALV-QtDFpSw", title: "Play It Again", artist: "Luke Bryan", genre: "country" },
  { code: "902", id: "CbxuXq_981s", title: "This Is How We Roll ft. Luke Bryan", artist: "Florida Georgia Line", genre: "country" },
  { code: "903", id: "IZbN_nmxAGk", title: "Whiskey Lullaby ft. Alison Krauss", artist: "Brad Paisley", genre: "country" },
  { code: "904", id: "6l3ukWqRU4s", title: "Huntin', Fishin', And Lovin' Every Day", artist: "Luke Bryan", genre: "country" },
  { code: "905", id: "e4ujS1er1r0", title: "Chicken Fried", artist: "Zac Brown Band", genre: "country" },
  { code: "906", id: "hvKyBcCDOB4", title: "Wagon Wheel", artist: "Darius Rucker", genre: "country" },
  { code: "907", id: "QrM39m22jH4", title: "Drunk On A Plane", artist: "Dierks Bentley", genre: "country" },
  { code: "908", id: "Lb9q1ScC4cg", title: "Dirt Road Anthem", artist: "Jason Aldean", genre: "country" },
  { code: "909", id: "p1oL37ycONQ", title: "Round Here", artist: "Florida Georgia Line", genre: "country" },
  { code: "910", id: "PT4ryVop_Fc", title: "May We All ft. Tim McGraw", artist: "Florida Georgia Line", genre: "country" },
  { code: "911", id: "i_XGnxTi-fE", title: "The Devil Went Down to Georgia", artist: "The Charlie Daniels Band", genre: "country" },
  { code: "912", id: "xdImDqbgc2g", title: "Burnin' It Down", artist: "Jason Aldean", genre: "country" },
  { code: "913", id: "HpFaI0dKAHc", title: "Drunk On You", artist: "Luke Bryan", genre: "country" },
  { code: "147", id: "3OnnDqH6Wj8", title: "Good Feeling", artist: "Flo Rida", genre: "pop" },
  { code: "914", id: "5tXh_MfrMe0", title: "Life Is a Highway", artist: "Rascal Flatts", genre: "country" },
  { code: "705", id: "Y66j_BUCBMY", title: "Best Day Of My Life", artist: "American Authors", genre: "indie" },
  { code: "148", id: "QJO3ROT-A4E", title: "What Makes You Beautiful", artist: "One Direction", genre: "pop" },
  { code: "149", id: "hHUbLv4ThOo", title: "Timber", artist: "Pitbull, Ke$ha", genre: "pop" },
  { code: "706", id: "mE6DLY7WQkg", title: "Waste", artist: "Foster The People", genre: "indie" },
  { code: "915", id: "42uphHWxmFU", title: "Dirt", artist: "Florida Georgia Line", genre: "country" },
  { code: "916", id: "8PvebsWcpto", title: "Cruise", artist: "Florida Georgia Line", genre: "country" },
  { code: "917", id: "oajuSNChUOo", title: "Get Your Shine On", artist: "Florida Georgia Line", genre: "country" },
  { code: "918", id: "ldQrapQ4d0Y", title: "As Good As I Once Was", artist: "Toby Keith", genre: "country" },
  { code: "919", id: "T_igmjEB560", title: "Stay", artist: "Florida Georgia Line", genre: "country" },
  { code: "920", id: "7qH4qyi1-Ys", title: "What Hurts The Most", artist: "Rascal Flatts", genre: "country" },
  { code: "921", id: "zXDAYlhdkyg", title: "H.O.L.Y.", artist: "Florida Georgia Line", genre: "country" },
  { code: "922", id: "8AHCfZTRGiI", title: "Hurt", artist: "Johnny Cash", genre: "country" },
  { code: "923", id: "-Fulz4ytZ54", title: "I Love This Bar", artist: "Toby Keith", genre: "country" },
  { code: "216", id: "3afXXsJwYZo", title: "Joker and the Thief", artist: "Wolfmother", genre: "rock" },
  { code: "306", id: "1LwaYHkNXdQ", title: "Edge of Seventeen", artist: "Stevie Nicks", genre: "80s" },
  { code: "924", id: "XHaVmFKnK7w", title: "Cry, Cry, Cry", artist: "Johnny Cash", genre: "country" },
  { code: "150", id: "-YICuUtkjlg", title: "Wrecking Ball", artist: "Miley Cyrus", genre: "pop" },
  { code: "217", id: "I_2D8Eo15wE", title: "Black Betty", artist: "Ram Jam", genre: "rock" },
  { code: "307", id: "-qvTFnLwWOM", title: "Automatic", artist: "The Pointer Sisters", genre: "80s" },
  { code: "707", id: "nlcIKh6sBtc", title: "Royals", artist: "Lorde", genre: "indie" },
  { code: "414", id: "O-zpOMYRi0w", title: "Fancy ft. Charli XCX", artist: "Iggy Azalea", genre: "hip-hop" },
  { code: "151", id: "qpgTC9MDx1o", title: "Animals", artist: "Maroon 5", genre: "pop" },
  { code: "925", id: "IH1Z9DEDqpk", title: "Why Don't We Just Dance", artist: "Josh Turner", genre: "country" },
  { code: "926", id: "-q0LE3gtUn8", title: "Lover, Lover", artist: "Jerrod Niemann", genre: "country" },
  { code: "927", id: "97BfC4LgrXk", title: "What Do You Want", artist: "Jerrod Niemann", genre: "country" },
  { code: "928", id: "MaAF_3WMJGM", title: "Made In America", artist: "Toby Keith", genre: "country" },
  { code: "929", id: "KmxaY_OVvWA", title: "Highway Don't Care ft. Taylor Swift, Keith Urban", artist: "Tim McGraw", genre: "country" },
  { code: "930", id: "_l0pqnBoozs", title: "Hell Raisin' Heat of the Summer", artist: "Florida Georgia Line", genre: "country" },
  { code: "931", id: "awzNHuGqoMc", title: "Humble And Kind", artist: "Tim McGraw", genre: "country" },
  { code: "152", id: "z3zdIHDTbg0", title: "Made in the USA", artist: "Demi Lovato", genre: "pop" },
  { code: "218", id: "UZm3Ad3gTSI", title: "The Unforgiven (Live, Madrid 2024)", artist: "Metallica", genre: "rock" },
  { code: "219", id: "912EG0VhCmk", title: "Fade to Black (Live, Phoenix 2023)", artist: "Metallica", genre: "rock" },
  { code: "153", id: "iP6XpLQM2Cs", title: "TiK ToK", artist: "Ke$ha", genre: "pop" },
  { code: "154", id: "WA4iX5D9Z64", title: "We Are Never Ever Getting Back Together", artist: "Taylor Swift", genre: "pop" },
  { code: "155", id: "7PCkvCPvDXk", title: "All About That Bass", artist: "Meghan Trainor", genre: "pop" },
  { code: "156", id: "4fndeDfaWCg", title: "I Want It That Way", artist: "Backstreet Boys", genre: "pop" },
  { code: "157", id: "bTXJQ5ql5Fw", title: "Time of Our Lives", artist: "Pitbull, Ne-Yo", genre: "pop" },
  { code: "158", id: "7Xf-Lesrkuc", title: "Drops Of Jupiter (Tell Me)", artist: "Train", genre: "pop" },
  { code: "708", id: "rprf7LEraU4", title: "Sleepwalking", artist: "The Chain Gang Of 1974", genre: "indie" },
  { code: "709", id: "N3zf9q8mbWs", title: "The Setup", artist: "Favored Nations", genre: "indie" },
  { code: "710", id: "d4KOfBx_XPM", title: "Don't Come Close", artist: "Yeasayer", genre: "indie" },
  { code: "308", id: "rXs9MXrHxVE", title: "Hit Me With Your Best Shot", artist: "Pat Benatar", genre: "80s" },
  { code: "309", id: "2AilA-M6N5U", title: "Love Is A Long Road", artist: "Tom Petty & The Heartbreakers", genre: "80s" },
  { code: "310", id: "wIiVp3poe2c", title: "The Power Of Love", artist: "Huey Lewis & The News", genre: "80s" },
  { code: "220", id: "CqnU_sJ8V-E", title: "Free Bird", artist: "Lynyrd Skynyrd", genre: "rock" },
  { code: "311", id: "qGBohd0V2Mo", title: "Video Killed The Radio Star", artist: "The Buggles", genre: "80s" },
  { code: "312", id: "valVixMpzQY", title: "One Way Or Another", artist: "Blondie", genre: "80s" },
  { code: "313", id: "SVOuYquXuuc", title: "Owner of a Lonely Heart", artist: "Yes", genre: "80s" },
  { code: "159", id: "qQzdAsjWGPg", title: "My Way", artist: "Frank Sinatra", genre: "pop" },
  { code: "221", id: "Aiay8I5IPB8", title: "How You Remind Me", artist: "Nickelback", genre: "rock" },
  { code: "222", id: "_1hgVcNzvzY", title: "Rockstar", artist: "Nickelback", genre: "rock" },
  { code: "223", id: "GP7zpdwo3Xo", title: "Far Away", artist: "Nickelback", genre: "rock" },
  { code: "224", id: "T3rXdeOvhNE", title: "Photograph", artist: "Nickelback", genre: "rock" },
  { code: "225", id: "_JQiEs32SqQ", title: "Savin' Me", artist: "Nickelback", genre: "rock" },
  { code: "226", id: "4bE7caE5UGc", title: "Next Contestant", artist: "Nickelback", genre: "rock" },
  { code: "160", id: "kffacxfA7G4", title: "Baby ft. Ludacris", artist: "Justin Bieber", genre: "pop" },
  { code: "227", id: "dZLfasMPOU4", title: "Stacy's Mom", artist: "Fountains Of Wayne", genre: "rock" },
  { code: "161", id: "75IMChOtf9s", title: "The Show Must Go On", artist: "Hazbin Hotel", genre: "pop" },
  { code: "162", id: "7OwRqCFuH9k", title: "Poison (Official Remix)", artist: "Hazbin Hotel", genre: "pop" },
  { code: "228", id: "8SbUC-UaAxE", title: "November Rain", artist: "Guns N' Roses", genre: "rock" },
  { code: "932", id: "-vn6QdqxK3g", title: "Don't Take The Girl", artist: "Tim McGraw", genre: "country" },
];
